import { PERMISSIONS } from '$lib/permissions/registry';

export const _meta = {
	academicContext: 'term_required' as const,
	menu: {
		title: 'กรอกคะแนนและประเมินผู้เรียน',
		icon: 'BookOpenCheck',
		group: 'academic_assessment',
		workspace: 'academic',
		order: 20,
		user_type: 'staff',
		permission: [
			PERMISSIONS.ACADEMIC_GRADEBOOK_READ_ASSIGNED,
			PERMISSIONS.ACADEMIC_GRADEBOOK_READ_ORGANIZATION_UNIT,
			PERMISSIONS.ACADEMIC_GRADEBOOK_READ_SCHOOL,
			PERMISSIONS.ACADEMIC_GRADEBOOK_MANAGE_ASSIGNED,
			PERMISSIONS.ACADEMIC_GRADEBOOK_MANAGE_SCHOOL,
			PERMISSIONS.ACADEMIC_LEARNER_EVALUATION_READ_ASSIGNED,
			PERMISSIONS.ACADEMIC_LEARNER_EVALUATION_READ_ORGANIZATION_UNIT,
			PERMISSIONS.ACADEMIC_LEARNER_EVALUATION_READ_SCHOOL,
			PERMISSIONS.ACADEMIC_LEARNER_EVALUATION_MANAGE_ASSIGNED,
			PERMISSIONS.ACADEMIC_LEARNER_EVALUATION_MANAGE_SCHOOL
		]
	}
};

export const load = async () => ({ title: _meta.menu.title });
