use axum::{
    extract::DefaultBodyLimit,
    middleware::{from_fn, from_fn_with_state},
    routing::{delete, get, post, put},
    Json, Router,
};
use serde_json::json;

use crate::{middleware, modules, AppState};

pub const AUTH_JSON_BODY_LIMIT: usize = 16 * 1024;
pub const APPLICATION_BODY_LIMIT: usize = 20 * 1024 * 1024;

pub fn build_app(state: AppState) -> Router {
    let runtime = state.auth_runtime.clone();
    public_routes()
        .merge(protected_routes().route_layer(from_fn_with_state(runtime, session_middleware)))
        .layer(DefaultBodyLimit::max(APPLICATION_BODY_LIMIT))
        .with_state(state)
}

fn public_routes() -> Router<AppState> {
    Router::new()
        .route("/", get(root_handler))
        .route(
            "/health",
            get(modules::system::handlers::health::health_check),
        )
        .route(
            "/ready",
            get(modules::system::handlers::health::readiness_check),
        )
        .route(
            "/api/public/calendar/events",
            get(modules::calendar::handlers::list_public_calendar_events),
        )
        .route(
            "/api/auth/login",
            post(modules::auth::session_handlers::login)
                .layer(DefaultBodyLimit::max(AUTH_JSON_BODY_LIMIT)),
        )
        .route(
            "/api/auth/logout",
            post(modules::auth::session_handlers::logout),
        )
        .route(
            "/api/consent/types",
            get(modules::consent::handlers::get_consent_types),
        )
        .route(
            "/api/public/files/{id}/content",
            get(modules::files::handlers::get_public_file_content),
        )
        .route(
            "/api/public/files/{id}/delivery",
            get(modules::files::handlers::get_public_file_delivery),
        )
        .nest(
            "/api/admission",
            modules::admission::admission_public_routes(),
        )
        .route(
            "/api/school/public",
            get(modules::school::handlers::get_public_info),
        )
        .route(
            "/api/admin/routes/sync",
            post(modules::system::handlers::register_routes::register_routes),
        )
        // WebSocket authentication runs in the handler; query selects semester only.
        .route(
            "/ws/timetable",
            get(modules::academic::websockets::timetable_websocket_handler),
        )
        .merge(internal_routes())
}

fn internal_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/internal/provision",
            post(modules::system::handlers::provision::provision_tenant),
        )
        .route(
            "/internal/migrate-all",
            post(modules::system::handlers::migration::migrate_all_schools),
        )
        .route(
            "/internal/migration-status",
            get(modules::system::handlers::migration::migration_status),
        )
        .route_layer(from_fn(middleware::internal_auth::validate_internal_secret))
}

fn protected_routes() -> Router<AppState> {
    Router::new()
        .route("/api/auth/me", get(modules::auth::session_handlers::me))
        .route(
            "/api/auth/me/profile",
            get(modules::auth::handlers::get_profile).put(modules::auth::handlers::update_profile),
        )
        .route(
            "/api/auth/me/change-password",
            post(modules::auth::session_handlers::change_password)
                .layer(DefaultBodyLimit::max(AUTH_JSON_BODY_LIMIT)),
        )
        .route(
            "/api/auth/sessions",
            get(modules::auth::session_handlers::list_sessions),
        )
        .route(
            "/api/auth/sessions/{id}",
            delete(modules::auth::session_handlers::revoke_session),
        )
        .route(
            "/api/auth/logout-all",
            post(modules::auth::session_handlers::logout_all),
        )
        .route(
            "/api/staff",
            get(modules::staff::handlers::staff::list_staff)
                .post(modules::staff::handlers::staff::create_staff),
        )
        .route(
            "/api/staff/dashboard",
            get(modules::staff::handlers::staff::get_staff_dashboard),
        )
        .route(
            "/api/staff/{id}",
            get(modules::staff::handlers::staff::get_staff_profile)
                .put(modules::staff::handlers::staff::update_staff)
                .delete(modules::staff::handlers::staff::delete_staff),
        )
        .route(
            "/api/staff/{id}/public-profile",
            get(modules::staff::handlers::staff::get_public_staff_profile),
        )
        .route(
            "/api/achievements",
            get(modules::achievement::handlers::list_achievements)
                .post(modules::achievement::handlers::create_achievement),
        )
        .route(
            "/api/achievements/{id}",
            put(modules::achievement::handlers::update_achievement)
                .delete(modules::achievement::handlers::delete_achievement),
        )
        .route(
            "/api/certificates/campaigns",
            get(modules::certificates::handlers::list_certificate_campaigns)
                .post(modules::certificates::handlers::create_certificate_campaign),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}",
            get(modules::certificates::handlers::get_certificate_campaign)
                .put(modules::certificates::handlers::update_certificate_campaign)
                .delete(modules::certificates::handlers::delete_certificate_campaign),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/status",
            put(modules::certificates::handlers::change_certificate_campaign_status),
        )
        .route(
            "/api/certificates/owner-options",
            get(modules::certificates::handlers::list_certificate_owner_options),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/templates",
            get(modules::certificates::handlers::list_certificate_templates)
                .post(modules::certificates::handlers::create_certificate_template),
        )
        .route(
            "/api/certificates/templates/{template_id}",
            get(modules::certificates::handlers::get_certificate_template)
                .put(modules::certificates::handlers::update_certificate_template)
                .delete(modules::certificates::handlers::delete_certificate_template),
        )
        .route(
            "/api/certificates/templates/{template_id}/background",
            put(modules::certificates::handlers::attach_certificate_template_background),
        )
        .route(
            "/api/certificates/templates/{template_id}/assets",
            post(modules::certificates::handlers::attach_certificate_template_asset),
        )
        .route(
            "/api/certificates/templates/{template_id}/assets/{asset_id}",
            delete(modules::certificates::handlers::delete_certificate_template_asset),
        )
        .route(
            "/api/certificates/templates/{template_id}/variables",
            get(modules::certificates::handlers::get_certificate_template_variable_catalog),
        )
        .route(
            "/api/certificates/templates/{template_id}/preview-manifest",
            post(modules::certificates::handlers::create_certificate_template_preview_manifest),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/candidates",
            get(modules::certificates::handlers::list_certificate_candidates),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/candidates/import",
            post(modules::certificates::handlers::import_certificate_candidates),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/candidates/manual",
            post(modules::certificates::handlers::create_manual_certificate_candidate),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/candidates/account-search",
            get(modules::certificates::handlers::search_certificate_candidate_accounts)
                .post(modules::certificates::handlers::create_account_certificate_candidate),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/candidates/bulk",
            post(modules::certificates::handlers::bulk_update_certificate_candidates),
        )
        .route(
            "/api/certificates/candidates/{candidate_id}",
            get(modules::certificates::handlers::get_certificate_candidate)
                .put(modules::certificates::handlers::update_certificate_candidate)
                .delete(modules::certificates::handlers::delete_certificate_candidate),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/issue-requests",
            get(modules::certificates::handlers::list_certificate_campaign_issue_requests)
                .post(modules::certificates::handlers::submit_certificate_issue_request),
        )
        .route(
            "/api/certificates/issue-requests",
            get(modules::certificates::handlers::list_certificate_issue_requests),
        )
        .route(
            "/api/certificates/issue-requests/{request_id}",
            get(modules::certificates::handlers::get_certificate_issue_request),
        )
        .route(
            "/api/certificates/issue-requests/{request_id}/withdraw",
            post(modules::certificates::handlers::withdraw_certificate_issue_request),
        )
        .route(
            "/api/certificates/issue-requests/{request_id}/review",
            post(modules::certificates::handlers::start_certificate_issue_request_review),
        )
        .route(
            "/api/certificates/issue-requests/{request_id}/return",
            post(modules::certificates::handlers::return_certificate_issue_request),
        )
        .route(
            "/api/certificates/issue-requests/{request_id}/issue",
            post(modules::certificates::handlers::issue_certificates),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/issued",
            get(modules::certificates::handlers::list_issued_certificates),
        )
        .route(
            "/api/certificates/campaigns/{campaign_id}/render-manifests",
            post(modules::certificates::handlers::create_issued_certificate_render_manifests),
        )
        .route(
            "/api/certificates/{certificate_id}",
            get(modules::certificates::handlers::get_issued_certificate),
        )
        .route(
            "/api/certificates/{certificate_id}/revoke",
            post(modules::certificates::handlers::revoke_issued_certificate),
        )
        .route(
            "/api/certificates/{certificate_id}/render-manifest",
            post(modules::certificates::handlers::create_issued_certificate_render_manifest),
        )
        .route(
            "/api/student/profile",
            get(modules::students::handlers::get_own_profile)
                .put(modules::students::handlers::update_own_profile),
        )
        .route(
            "/api/parent/profile",
            get(modules::parents::handlers::get_own_parent_profile),
        )
        .route(
            "/api/parent/students/{student_id}",
            get(modules::parents::handlers::get_child_profile),
        )
        .route(
            "/api/parent/students/{student_id}/timetable",
            get(modules::parents::handlers::get_child_timetable),
        )
        .route(
            "/api/parent/students/{student_id}/exam-schedules",
            get(modules::parents::handlers::get_child_exam_schedule),
        )
        .route(
            "/api/parent/students/{student_id}/calendar/events",
            get(modules::parents::handlers::get_child_calendar_events),
        )
        .route(
            "/api/me/timetable",
            get(modules::academic::handlers::timetable::get_my_timetable),
        )
        .route(
            "/api/me/exam-schedules",
            get(modules::academic::handlers::exam_schedule::list_my_exam_schedule),
        )
        .route(
            "/api/staff/exam-schedules",
            get(modules::academic::handlers::exam_schedule::list_staff_exam_schedule),
        )
        .route(
            "/api/me/calendar/events",
            get(modules::calendar::handlers::list_my_calendar_events),
        )
        .route(
            "/api/students",
            get(modules::students::handlers::list_students)
                .post(modules::students::handlers::create_student),
        )
        .route(
            "/api/students/{id}",
            get(modules::students::handlers::get_student)
                .put(modules::students::handlers::update_student)
                .delete(modules::students::handlers::delete_student),
        )
        .route(
            "/api/students/{id}/parents",
            post(modules::students::handlers_parents::add_parent_to_student),
        )
        .route(
            "/api/students/{id}/parents/{parent_id}",
            delete(modules::students::handlers_parents::remove_parent_from_student),
        )
        .route(
            "/api/roles",
            get(modules::staff::handlers::roles::list_roles)
                .post(modules::staff::handlers::roles::create_role),
        )
        .route(
            "/api/roles/{id}",
            get(modules::staff::handlers::roles::get_role)
                .put(modules::staff::handlers::roles::update_role)
                .delete(modules::staff::handlers::roles::deactivate_role),
        )
        .route(
            "/api/organization/units",
            get(modules::staff::handlers::roles::list_organization_units)
                .post(modules::staff::handlers::roles::create_organization_unit),
        )
        .route(
            "/api/organization/units/{id}",
            get(modules::staff::handlers::roles::get_organization_unit)
                .put(modules::staff::handlers::roles::update_organization_unit)
                .delete(modules::staff::handlers::roles::deactivate_organization_unit),
        )
        .route(
            "/api/organization/units/{id}/permissions",
            get(modules::staff::handlers::organization_permissions::get_organization_permissions)
                .put(
                modules::staff::handlers::organization_permissions::update_organization_permissions,
            ),
        )
        .route(
            "/api/organization/units/{id}/delegatable-permissions",
            get(modules::staff::handlers::organization_delegations::list_delegatable_permissions),
        )
        .route(
            "/api/organization/units/{id}/delegations",
            get(modules::staff::handlers::organization_delegations::list_delegations)
                .post(modules::staff::handlers::organization_delegations::create_delegation),
        )
        .route(
            "/api/organization/delegations/{id}",
            delete(modules::staff::handlers::organization_delegations::revoke_delegation),
        )
        .route(
            "/api/organization/units/{id}/members",
            get(modules::staff::handlers::organization_members::list_members)
                .post(modules::staff::handlers::organization_members::add_member),
        )
        .route(
            "/api/organization/units/{id}/members/{user_id}",
            put(modules::staff::handlers::organization_members::update_member)
                .delete(modules::staff::handlers::organization_members::remove_member),
        )
        .route(
            "/api/users/{id}/roles",
            get(modules::staff::handlers::user_roles::get_user_roles)
                .post(modules::staff::handlers::user_roles::assign_user_role),
        )
        .route(
            "/api/users/{id}/roles/{role_id}",
            delete(modules::staff::handlers::user_roles::remove_user_role),
        )
        .route(
            "/api/users/{id}/permissions",
            get(modules::staff::handlers::user_roles::get_user_permissions),
        )
        .route(
            "/api/permissions",
            get(modules::staff::handlers::permissions::list_permissions),
        )
        .route(
            "/api/permissions/modules",
            get(modules::staff::handlers::permissions::list_permissions_by_module),
        )
        .route(
            "/api/menu/user",
            get(modules::menu::handlers::public::get_user_menu),
        )
        .route(
            "/api/admin/features",
            get(modules::system::handlers::feature_toggles::list_features),
        )
        .route(
            "/api/admin/features/{id}",
            get(modules::system::handlers::feature_toggles::get_feature)
                .put(modules::system::handlers::feature_toggles::update_feature),
        )
        .route(
            "/api/admin/features/{id}/toggle",
            post(modules::system::handlers::feature_toggles::toggle_feature),
        )
        .route(
            "/api/admin/menu/workspaces",
            get(modules::menu::handlers::admin::list_menu_workspaces)
                .post(modules::menu::handlers::admin::create_menu_workspace),
        )
        .route(
            "/api/admin/menu/workspaces/reorder",
            post(modules::menu::handlers::admin::reorder_menu_workspaces),
        )
        .route(
            "/api/admin/menu/workspaces/{id}",
            put(modules::menu::handlers::admin::update_menu_workspace)
                .delete(modules::menu::handlers::admin::delete_menu_workspace),
        )
        .route(
            "/api/admin/menu/groups",
            get(modules::menu::handlers::admin::list_menu_groups)
                .post(modules::menu::handlers::admin::create_menu_group),
        )
        .route(
            "/api/admin/menu/groups/{id}",
            put(modules::menu::handlers::admin::update_menu_group)
                .delete(modules::menu::handlers::admin::delete_menu_group),
        )
        .route(
            "/api/admin/menu/groups/reorder",
            post(modules::menu::handlers::admin::reorder_menu_groups),
        )
        .route(
            "/api/admin/menu/items",
            get(modules::menu::handlers::admin::list_menu_items)
                .post(modules::menu::handlers::admin::create_menu_item),
        )
        .route(
            "/api/admin/menu/items/{id}",
            put(modules::menu::handlers::admin::update_menu_item)
                .delete(modules::menu::handlers::admin::delete_menu_item),
        )
        .route(
            "/api/admin/menu/items/{id}/group",
            put(modules::menu::handlers::admin::move_item_to_group),
        )
        .route(
            "/api/admin/menu/items/reorder",
            post(modules::menu::handlers::admin::reorder_menu_items),
        )
        .route(
            "/api/consent/my-status",
            get(modules::consent::handlers::get_my_consent_status),
        )
        .route(
            "/api/consent",
            post(modules::consent::handlers::create_consent),
        )
        .route(
            "/api/consent/{id}/withdraw",
            post(modules::consent::handlers::withdraw_consent),
        )
        .route(
            "/api/consent/summary",
            get(modules::consent::handlers::get_consent_summary),
        )
        .route(
            "/api/files",
            post(modules::files::handlers::upload_file)
                .layer(DefaultBodyLimit::max(24 * 1024 * 1024)),
        )
        .route(
            "/api/files/{id}",
            get(modules::files::handlers::get_file_metadata)
                .delete(modules::files::handlers::delete_file),
        )
        .route(
            "/api/files/{id}/download",
            post(modules::files::handlers::download_file),
        )
        .nest("/api/academic", modules::academic::academic_routes())
        .nest("/api/calendar", modules::calendar::calendar_routes())
        .nest(
            "/api/supervision",
            modules::supervision::supervision_routes(),
        )
        .nest("/api/facilities", modules::facility::facility_routes())
        .nest("/api", modules::workflow::workflow_routes())
        .nest("/api", modules::work::work_routes())
        .nest(
            "/api/admission",
            modules::admission::admission_staff_routes(),
        )
        .route(
            "/api/school/settings",
            get(modules::school::handlers::get_settings)
                .patch(modules::school::handlers::update_settings),
        )
        .route(
            "/api/school/settings/logo",
            delete(modules::school::handlers::delete_logo),
        )
        .route(
            "/api/notifications/stream",
            get(modules::notification::handlers::stream_notifications),
        )
        .route(
            "/api/notifications",
            get(modules::notification::handlers::list_notifications)
                .post(modules::notification::handlers::create_notification),
        )
        .route(
            "/api/notifications/read-all",
            post(modules::notification::handlers::mark_all_as_read),
        )
        .route(
            "/api/notifications/{id}/read",
            post(modules::notification::handlers::mark_as_read),
        )
        .route(
            "/api/notifications/subscribe",
            post(modules::notification::handlers::subscribe_push),
        )
        .route(
            "/api/lookup/staff",
            get(modules::lookup::handlers::lookup_staff),
        )
        .route(
            "/api/lookup/students",
            get(modules::lookup::handlers::lookup_students),
        )
        .route(
            "/api/lookup/rooms",
            get(modules::lookup::handlers::lookup_rooms),
        )
        .route(
            "/api/lookup/roles",
            get(modules::lookup::handlers::lookup_roles),
        )
        .route(
            "/api/lookup/organization-units",
            get(modules::lookup::handlers::lookup_organization_units),
        )
        .route(
            "/api/lookup/organization-units/{id}",
            get(modules::lookup::handlers::lookup_organization_unit_by_id),
        )
        .route(
            "/api/lookup/grade-levels",
            get(modules::lookup::handlers::lookup_grade_levels),
        )
        .route(
            "/api/lookup/classrooms",
            get(modules::lookup::handlers::lookup_classrooms),
        )
        .route(
            "/api/lookup/academic-years",
            get(modules::lookup::handlers::lookup_academic_years),
        )
        .route(
            "/api/lookup/subjects",
            get(modules::lookup::handlers::lookup_subjects),
        )
}

async fn root_handler() -> Json<serde_json::Value> {
    Json(json!({
        "service": "SchoolOrbit Backend School",
        "version": "0.2.0",
        "status": "running",
        "architecture": "multi-tenant with dynamic connection pools"
    }))
}

use crate::middleware::session::session_middleware;
