pub mod handlers;
pub mod models;
pub mod services;

use crate::AppState;
use axum::routing::{get, post};
use axum::Router;

pub fn routes() -> Router<AppState> {
    Router::new()
        .route("/context/options", get(handlers::list_context_options))
        .route(
            "/setup/workspace",
            get(handlers::get_academic_setup_workspace),
        )
        .route(
            "/years",
            get(handlers::list_years).post(handlers::create_year),
        )
        .route(
            "/years/{id}",
            get(handlers::get_year).patch(handlers::update_year),
        )
        .route(
            "/terms",
            get(handlers::list_terms).post(handlers::create_term),
        )
        .route(
            "/terms/{id}",
            get(handlers::get_term)
                .patch(handlers::update_term)
                .delete(handlers::delete_term),
        )
        .route(
            "/bell-schedules",
            get(handlers::list_bell_schedules).post(handlers::create_bell_schedule),
        )
        .route(
            "/bell-schedules/{id}",
            get(handlers::get_bell_schedule).patch(handlers::update_bell_schedule),
        )
        .route(
            "/bell-schedules/{id}/periods",
            get(handlers::list_bell_schedule_periods).put(handlers::replace_bell_schedule_periods),
        )
        .route(
            "/grade-progressions",
            get(handlers::list_grade_progressions).put(handlers::replace_grade_progressions),
        )
        .route(
            "/catalog/subjects",
            get(handlers::list_catalog_subjects).post(handlers::create_catalog_subject),
        )
        .route(
            "/catalog/subjects/overview",
            get(handlers::get_catalog_subject_overview),
        )
        .route(
            "/catalog/subjects/{id}",
            get(handlers::get_catalog_subject).patch(handlers::update_catalog_subject),
        )
        .route(
            "/catalog/subjects/{id}/versions",
            get(handlers::list_subject_versions).post(handlers::create_subject_version),
        )
        .route(
            "/catalog/subject-versions/{id}",
            get(handlers::get_subject_version).patch(handlers::update_subject_version),
        )
        .route(
            "/catalog/subject-versions/{id}/publish",
            post(handlers::publish_subject_version),
        )
        .route(
            "/catalog/subjects/{id}/default-teachers",
            get(handlers::list_subject_default_teachers)
                .put(handlers::replace_subject_default_teachers),
        )
        .route(
            "/catalog/subject-groups",
            get(handlers::list_subject_groups).post(handlers::create_subject_group),
        )
        .route(
            "/catalog/subject-groups/{id}",
            get(handlers::get_subject_group)
                .patch(handlers::update_subject_group)
                .delete(handlers::delete_subject_group),
        )
        .route(
            "/catalog/activities",
            get(handlers::list_catalog_activities).post(handlers::create_catalog_activity),
        )
        .route(
            "/catalog/activities/overview",
            get(handlers::get_catalog_activity_overview),
        )
        .route(
            "/catalog/activities/{id}",
            get(handlers::get_catalog_activity).patch(handlers::update_catalog_activity),
        )
        .route(
            "/catalog/activities/{id}/versions",
            get(handlers::list_activity_versions).post(handlers::create_activity_version),
        )
        .route(
            "/catalog/activity-versions/{id}",
            get(handlers::get_activity_version).patch(handlers::update_activity_version),
        )
        .route(
            "/catalog/activity-versions/{id}/publish",
            post(handlers::publish_activity_version),
        )
        .route(
            "/catalog/activities/{id}/default-teachers",
            get(handlers::list_activity_default_teachers)
                .put(handlers::replace_activity_default_teachers),
        )
        .route(
            "/curricula",
            get(handlers::list_curricula).post(handlers::create_curriculum),
        )
        .route(
            "/curricula/overview",
            get(handlers::get_curriculum_overview),
        )
        .route(
            "/curricula/management-options",
            get(handlers::get_curriculum_create_options),
        )
        .route(
            "/study-program-options",
            get(handlers::list_study_program_options_for_year),
        )
        .route(
            "/curricula/{id}",
            get(handlers::get_curriculum).patch(handlers::update_curriculum),
        )
        .route(
            "/curricula/{id}/versions",
            get(handlers::list_curriculum_versions).post(handlers::create_curriculum_version),
        )
        .route(
            "/curriculum-versions/{id}",
            get(handlers::get_curriculum_version).patch(handlers::update_curriculum_version),
        )
        .route(
            "/curriculum-versions/{id}/management-options",
            get(handlers::get_curriculum_management_options),
        )
        .route(
            "/curriculum-versions/{id}/publish",
            post(handlers::publish_curriculum_version),
        )
        .route(
            "/curriculum-versions/{id}/program-workspace",
            get(handlers::get_curriculum_program_workspace),
        )
        .route(
            "/curriculum-versions/{id}/programs",
            get(handlers::list_study_programs).post(handlers::create_study_program),
        )
        .route(
            "/study-programs/{id}",
            get(handlers::get_study_program).patch(handlers::update_study_program),
        )
        .route(
            "/study-programs/{id}/requirements",
            get(handlers::list_program_requirements).put(handlers::replace_program_requirements),
        )
        .route(
            "/homerooms",
            get(handlers::list_homerooms).post(handlers::create_homeroom),
        )
        .route(
            "/homerooms/{id}",
            get(handlers::get_homeroom).patch(handlers::update_homeroom),
        )
        .route(
            "/homerooms/{id}/advisors",
            get(handlers::list_homeroom_advisors).put(handlers::replace_homeroom_advisors),
        )
        .route(
            "/homeroom-advisors",
            get(handlers::list_homeroom_advisors_for_year),
        )
        .route(
            "/student-years",
            get(handlers::list_student_years).post(handlers::create_student_year),
        )
        .route(
            "/student-years/candidates",
            get(handlers::list_student_year_candidates),
        )
        .route(
            "/student-years/{id}",
            get(handlers::get_student_year).patch(handlers::update_student_year),
        )
        .route(
            "/student-years/{id}/placements",
            get(handlers::list_placements).post(handlers::create_placement),
        )
        .route("/placements", get(handlers::list_placements_for_year))
        .route(
            "/placements/{id}/transfer",
            post(handlers::transfer_placement),
        )
}

#[cfg(test)]
mod schema_tests;
#[cfg(test)]
mod services_tests;
