[package]
name = "backend-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
futures = "0.3.34"
tower = "0.5.3"
tower-cookies = "0.11"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "postgres", "macros", "migrate", "chrono", "uuid", "json", "tls-native-tls"] }
jsonwebtoken = "9.3.1"
bcrypt = "0.15.1"
dotenv = "0.15"
chrono = { version = "0.4.45", features = ["serde"] }
uuid = { version = "1.26.1", features = ["serde", "v4"] }
reqwest = { version = "0.13.5", default-features = false, features = ["json", "query", "native-tls", "charset", "http2", "system-proxy"] }
cookie = "0.18.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
subtle = "2.6.1"
