// @generated by scripts/generate-permissions.mjs; DO NOT EDIT.
// contract-sha256: bea559099555a56263828fcf8726d4e02a5c95942b0d0d8785cec64c72a484f5

pub mod codes {
    pub const WILDCARD: &str = "*";
    pub const ACADEMIC_ASSESSMENT_MANAGE_ASSIGNED: &str = "academic_assessment.manage.assigned";
    pub const ACADEMIC_ASSESSMENT_MANAGE_SCHOOL: &str = "academic_assessment.manage.school";
    pub const ACADEMIC_ASSESSMENT_READ_ASSIGNED: &str = "academic_assessment.read.assigned";
    pub const ACADEMIC_ASSESSMENT_READ_ORGANIZATION_UNIT: &str =
        "academic_assessment.read.organization_unit";
    pub const ACADEMIC_ASSESSMENT_READ_SCHOOL: &str = "academic_assessment.read.school";
    pub const ACADEMIC_CATALOG_MANAGE_ORGANIZATION_TREE: &str =
        "academic_catalog.manage.organization_tree";
    pub const ACADEMIC_CATALOG_MANAGE_ORGANIZATION_UNIT: &str =
        "academic_catalog.manage.organization_unit";
    pub const ACADEMIC_CATALOG_MANAGE_SCHOOL: &str = "academic_catalog.manage.school";
    pub const ACADEMIC_CATALOG_READ_SCHOOL: &str = "academic_catalog.read.school";
    pub const ACADEMIC_CONTEXT_READ_SCHOOL: &str = "academic_context.read.school";
    pub const ACADEMIC_CURRICULUM_MANAGE_ORGANIZATION_TREE: &str =
        "academic_curriculum.manage.organization_tree";
    pub const ACADEMIC_CURRICULUM_MANAGE_ORGANIZATION_UNIT: &str =
        "academic_curriculum.manage.organization_unit";
    pub const ACADEMIC_CURRICULUM_MANAGE_SCHOOL: &str = "academic_curriculum.manage.school";
    pub const ACADEMIC_CURRICULUM_READ_ORGANIZATION_TREE: &str =
        "academic_curriculum.read.organization_tree";
    pub const ACADEMIC_CURRICULUM_READ_ORGANIZATION_UNIT: &str =
        "academic_curriculum.read.organization_unit";
    pub const ACADEMIC_CURRICULUM_READ_SCHOOL: &str = "academic_curriculum.read.school";
    pub const ACADEMIC_EXAM_SCHEDULE_MANAGE_SCHOOL: &str = "academic_exam_schedule.manage.school";
    pub const ACADEMIC_EXAM_SCHEDULE_PUBLISH_SCHOOL: &str = "academic_exam_schedule.publish.school";
    pub const ACADEMIC_EXAM_SCHEDULE_READ_SCHOOL: &str = "academic_exam_schedule.read.school";
    pub const ACADEMIC_QUESTION_BANK_MANAGE_ASSIGNED: &str =
        "academic_question_bank.manage.assigned";
    pub const ACADEMIC_QUESTION_BANK_MANAGE_ORGANIZATION_UNIT: &str =
        "academic_question_bank.manage.organization_unit";
    pub const ACADEMIC_QUESTION_BANK_MANAGE_SCHOOL: &str = "academic_question_bank.manage.school";
    pub const ACADEMIC_QUESTION_BANK_READ_ASSIGNED: &str = "academic_question_bank.read.assigned";
    pub const ACADEMIC_QUESTION_BANK_READ_ORGANIZATION_UNIT: &str =
        "academic_question_bank.read.organization_unit";
    pub const ACADEMIC_QUESTION_BANK_READ_SCHOOL: &str = "academic_question_bank.read.school";
    pub const ACADEMIC_TERM_MANAGE_SCHOOL: &str = "academic_term.manage.school";
    pub const ACADEMIC_TERM_READ_SCHOOL: &str = "academic_term.read.school";
    pub const ACADEMIC_TIMETABLE_TODAY_READ_SCHOOL: &str = "academic_timetable_today.read.school";
    pub const ACADEMIC_YEAR_MANAGE_SCHOOL: &str = "academic_year.manage.school";
    pub const ACADEMIC_YEAR_READ_SCHOOL: &str = "academic_year.read.school";
    pub const ACHIEVEMENT_CREATE_ALL: &str = "achievement.create.all";
    pub const ACHIEVEMENT_CREATE_OWN: &str = "achievement.create.own";
    pub const ACHIEVEMENT_DELETE_ALL: &str = "achievement.delete.all";
    pub const ACHIEVEMENT_DELETE_OWN: &str = "achievement.delete.own";
    pub const ACHIEVEMENT_READ_ALL: &str = "achievement.read.all";
    pub const ACHIEVEMENT_READ_OWN: &str = "achievement.read.own";
    pub const ACHIEVEMENT_UPDATE_ALL: &str = "achievement.update.all";
    pub const ACHIEVEMENT_UPDATE_OWN: &str = "achievement.update.own";
    pub const ADMISSION_ENROLL_ALL: &str = "admission.enroll.all";
    pub const ADMISSION_MANAGE_ALL: &str = "admission.manage.all";
    pub const ADMISSION_READ_ALL: &str = "admission.read.all";
    pub const ADMISSION_SCORES_ALL: &str = "admission.scores.all";
    pub const ADMISSION_VERIFY_ALL: &str = "admission.verify.all";
    pub const CALENDAR_MANAGE_SCHOOL: &str = "calendar.manage.school";
    pub const CALENDAR_READ_SCHOOL: &str = "calendar.read.school";
    pub const CERTIFICATE_CREATE_ORGANIZATION_UNIT: &str = "certificate.create.organization_unit";
    pub const CERTIFICATE_CREATE_SCHOOL: &str = "certificate.create.school";
    pub const CERTIFICATE_DELETE_ORGANIZATION_UNIT: &str = "certificate.delete.organization_unit";
    pub const CERTIFICATE_DELETE_SCHOOL: &str = "certificate.delete.school";
    pub const CERTIFICATE_DOWNLOAD_ORGANIZATION_UNIT: &str =
        "certificate.download.organization_unit";
    pub const CERTIFICATE_DOWNLOAD_SCHOOL: &str = "certificate.download.school";
    pub const CERTIFICATE_ISSUE_SCHOOL: &str = "certificate.issue.school";
    pub const CERTIFICATE_READ_ORGANIZATION_UNIT: &str = "certificate.read.organization_unit";
    pub const CERTIFICATE_READ_OWN: &str = "certificate.read.own";
    pub const CERTIFICATE_READ_SCHOOL: &str = "certificate.read.school";
    pub const CERTIFICATE_REVOKE_SCHOOL: &str = "certificate.revoke.school";
    pub const CERTIFICATE_SUBMIT_ORGANIZATION_UNIT: &str = "certificate.submit.organization_unit";
    pub const CERTIFICATE_SUBMIT_SCHOOL: &str = "certificate.submit.school";
    pub const CERTIFICATE_UPDATE_ORGANIZATION_UNIT: &str = "certificate.update.organization_unit";
    pub const CERTIFICATE_UPDATE_SCHOOL: &str = "certificate.update.school";
    pub const DASHBOARD_READ_OWN: &str = "dashboard.read.own";
    pub const FACILITY_CREATE_ALL: &str = "facility.create.all";
    pub const FACILITY_DELETE_ALL: &str = "facility.delete.all";
    pub const FACILITY_READ_ALL: &str = "facility.read.all";
    pub const FACILITY_UPDATE_ALL: &str = "facility.update.all";
    pub const FEATURES_READ_ALL: &str = "features.read.all";
    pub const FEATURES_UPDATE_ALL: &str = "features.update.all";
    pub const FONT_MANAGE_SCHOOL: &str = "font.manage.school";
    pub const HOMEROOM_MANAGE_SCHOOL: &str = "homeroom.manage.school";
    pub const HOMEROOM_READ_SCHOOL: &str = "homeroom.read.school";
    pub const LEARNING_OFFERING_MANAGE_ASSIGNED: &str = "learning_offering.manage.assigned";
    pub const LEARNING_OFFERING_MANAGE_ORGANIZATION_TREE: &str =
        "learning_offering.manage.organization_tree";
    pub const LEARNING_OFFERING_MANAGE_ORGANIZATION_UNIT: &str =
        "learning_offering.manage.organization_unit";
    pub const LEARNING_OFFERING_MANAGE_SCHOOL: &str = "learning_offering.manage.school";
    pub const LEARNING_OFFERING_READ_ASSIGNED: &str = "learning_offering.read.assigned";
    pub const LEARNING_OFFERING_READ_ORGANIZATION_TREE: &str =
        "learning_offering.read.organization_tree";
    pub const LEARNING_OFFERING_READ_ORGANIZATION_UNIT: &str =
        "learning_offering.read.organization_unit";
    pub const LEARNING_OFFERING_READ_SCHOOL: &str = "learning_offering.read.school";
    pub const MENU_CREATE_ALL: &str = "menu.create.all";
    pub const MENU_DELETE_ALL: &str = "menu.delete.all";
    pub const MENU_READ_ALL: &str = "menu.read.all";
    pub const MENU_UPDATE_ALL: &str = "menu.update.all";
    pub const ORGANIZATION_WORK_APPROVE_ORGANIZATION_UNIT: &str =
        "organization_work.approve.organization_unit";
    pub const ORGANIZATION_WORK_CREATE_OWN: &str = "organization_work.create.own";
    pub const ORGANIZATION_WORK_READ_ORGANIZATION_UNIT: &str =
        "organization_work.read.organization_unit";
    pub const ORGANIZATION_WORK_READ_OWN: &str = "organization_work.read.own";
    pub const ORGANIZATION_WORK_UPDATE_OWN: &str = "organization_work.update.own";
    pub const ROLES_ASSIGN_ALL: &str = "roles.assign.all";
    pub const ROLES_CREATE_ALL: &str = "roles.create.all";
    pub const ROLES_DELETE_ALL: &str = "roles.delete.all";
    pub const ROLES_READ_ALL: &str = "roles.read.all";
    pub const ROLES_REMOVE_ALL: &str = "roles.remove.all";
    pub const ROLES_UPDATE_ALL: &str = "roles.update.all";
    pub const SETTINGS_READ_ALL: &str = "settings.read.all";
    pub const SETTINGS_UPDATE_ALL: &str = "settings.update.all";
    pub const STAFF_CREATE_ALL: &str = "staff.create.all";
    pub const STAFF_DELETE_ALL: &str = "staff.delete.all";
    pub const STAFF_PII_READ_OWN: &str = "staff_pii.read.own";
    pub const STAFF_PII_READ_SCHOOL: &str = "staff_pii.read.school";
    pub const STAFF_PROFILE_READ_ORGANIZATION_TREE: &str = "staff_profile.read.organization_tree";
    pub const STAFF_PROFILE_READ_ORGANIZATION_UNIT: &str = "staff_profile.read.organization_unit";
    pub const STAFF_PROFILE_READ_OWN: &str = "staff_profile.read.own";
    pub const STAFF_PROFILE_READ_SCHOOL: &str = "staff_profile.read.school";
    pub const STAFF_READ_ALL: &str = "staff.read.all";
    pub const STAFF_UPDATE_ALL: &str = "staff.update.all";
    pub const STUDENT_ACADEMIC_YEAR_MANAGE_SCHOOL: &str = "student_academic_year.manage.school";
    pub const STUDENT_ACADEMIC_YEAR_READ_SCHOOL: &str = "student_academic_year.read.school";
    pub const STUDENT_CREATE_ALL: &str = "student.create.all";
    pub const STUDENT_DELETE_ALL: &str = "student.delete.all";
    pub const STUDENT_PII_READ_ASSIGNED: &str = "student_pii.read.assigned";
    pub const STUDENT_PII_READ_OWN: &str = "student_pii.read.own";
    pub const STUDENT_PII_READ_SCHOOL: &str = "student_pii.read.school";
    pub const STUDENT_READ_ASSIGNED: &str = "student.read.assigned";
    pub const STUDENT_READ_OWN: &str = "student.read.own";
    pub const STUDENT_READ_SCHOOL: &str = "student.read.school";
    pub const STUDENT_UPDATE_ALL: &str = "student.update.all";
    pub const STUDENT_UPDATE_OWN: &str = "student.update.own";
    pub const SUPERVISION_APPROVE_SCHOOL: &str = "supervision.approve.school";
    pub const SUPERVISION_EVALUATE_ASSIGNED: &str = "supervision.evaluate.assigned";
    pub const SUPERVISION_MANAGE_ORGANIZATION_TREE: &str = "supervision.manage.organization_tree";
    pub const SUPERVISION_MANAGE_ORGANIZATION_UNIT: &str = "supervision.manage.organization_unit";
    pub const SUPERVISION_MANAGE_SCHOOL: &str = "supervision.manage.school";
    pub const SUPERVISION_READ_ASSIGNED: &str = "supervision.read.assigned";
    pub const SUPERVISION_READ_ORGANIZATION_TREE: &str = "supervision.read.organization_tree";
    pub const SUPERVISION_READ_ORGANIZATION_UNIT: &str = "supervision.read.organization_unit";
    pub const SUPERVISION_READ_OWN: &str = "supervision.read.own";
    pub const SUPERVISION_READ_SCHOOL: &str = "supervision.read.school";
    pub const SUPERVISION_REQUEST_OWN: &str = "supervision.request.own";
}

pub const ALL_PERMISSIONS: &[PermissionDef] = &[
    PermissionDef {
        code: codes::WILDCARD,
        name: "Super Admin Access",
        module: "system",
        action: "all",
        scope: "global",
        description: "สิทธิ์ระดับสูงสุด (เข้าถึงทุกส่วน)",
    },
    PermissionDef {
        code: codes::ACADEMIC_ASSESSMENT_MANAGE_ASSIGNED,
        name: "จัดโครงสร้างคะแนนรายวิชาที่รับผิดชอบ",
        module: "academic_assessment",
        action: "manage",
        scope: "assigned",
        description: "เพิ่ม/แก้ไข/ส่งโครงสร้างคะแนนของรายวิชาที่ตนเองเป็นครูผู้สอน",
    },
    PermissionDef {
        code: codes::ACADEMIC_ASSESSMENT_MANAGE_SCHOOL,
        name: "จัดการโครงสร้างคะแนนทั้งโรงเรียน",
        module: "academic_assessment",
        action: "manage",
        scope: "school",
        description: "จัดการโครงสร้างคะแนนและสถานะการส่งของรายวิชาที่เปิดสอนทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_ASSESSMENT_READ_ASSIGNED,
        name: "ดูโครงสร้างคะแนนรายวิชาที่รับผิดชอบ",
        module: "academic_assessment",
        action: "read",
        scope: "assigned",
        description: "ดูโครงสร้างคะแนนของรายวิชาที่ตนเองเป็นครูผู้สอน",
    },
    PermissionDef {
        code: codes::ACADEMIC_ASSESSMENT_READ_ORGANIZATION_UNIT,
        name: "ดูโครงสร้างคะแนนในกลุ่มสาระ",
        module: "academic_assessment",
        action: "read",
        scope: "organization_unit",
        description: "ดูโครงสร้างคะแนนของรายวิชาในกลุ่มสาระเดียวกันแบบอ่านอย่างเดียว",
    },
    PermissionDef {
        code: codes::ACADEMIC_ASSESSMENT_READ_SCHOOL,
        name: "ดูภาพรวมโครงสร้างคะแนนทั้งโรงเรียน",
        module: "academic_assessment",
        action: "read",
        scope: "school",
        description: "ดูภาพรวมโครงสร้างคะแนนและรูปแบบการสอบของรายวิชาที่เปิดสอนทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_CATALOG_MANAGE_ORGANIZATION_TREE,
        name: "จัดการคลังวิชาในสายงาน",
        module: "academic_catalog",
        action: "manage",
        scope: "organization_tree",
        description: "จัดการรายการในคลังที่หน่วยงานของตนหรือหน่วยงานย่อยเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::ACADEMIC_CATALOG_MANAGE_ORGANIZATION_UNIT,
        name: "จัดการคลังวิชาของหน่วยงาน",
        module: "academic_catalog",
        action: "manage",
        scope: "organization_unit",
        description: "จัดการรายการในคลังที่หน่วยงานของตนเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::ACADEMIC_CATALOG_MANAGE_SCHOOL,
        name: "จัดการคลังวิชาทั้งโรงเรียน",
        module: "academic_catalog",
        action: "manage",
        scope: "school",
        description: "จัดการรายวิชาและกิจกรรมในคลังกลางทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_CATALOG_READ_SCHOOL,
        name: "ดูคลังวิชาและกิจกรรม",
        module: "academic_catalog",
        action: "read",
        scope: "school",
        description: "ดูรายวิชาและกิจกรรมพัฒนาผู้เรียนในคลังกลางของโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_CONTEXT_READ_SCHOOL,
        name: "ดูตัวเลือกปีและภาคเรียน",
        module: "academic_context",
        action: "read",
        scope: "school",
        description: "ดูชื่อและสถานะของปีการศึกษาและภาคเรียนที่ใช้เลือกบริบทการทำงาน",
    },
    PermissionDef {
        code: codes::ACADEMIC_CURRICULUM_MANAGE_ORGANIZATION_TREE,
        name: "จัดการหลักสูตรในสายงาน",
        module: "academic_curriculum",
        action: "manage",
        scope: "organization_tree",
        description: "จัดการหลักสูตรที่หน่วยงานของตนหรือหน่วยงานย่อยเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::ACADEMIC_CURRICULUM_MANAGE_ORGANIZATION_UNIT,
        name: "จัดการหลักสูตรของหน่วยงาน",
        module: "academic_curriculum",
        action: "manage",
        scope: "organization_unit",
        description: "จัดการหลักสูตรที่หน่วยงานของตนเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::ACADEMIC_CURRICULUM_MANAGE_SCHOOL,
        name: "จัดการหลักสูตรทั้งโรงเรียน",
        module: "academic_curriculum",
        action: "manage",
        scope: "school",
        description: "จัดการหลักสูตรทั้งหมดของโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_CURRICULUM_READ_ORGANIZATION_TREE,
        name: "ดูหลักสูตรในสายงาน",
        module: "academic_curriculum",
        action: "read",
        scope: "organization_tree",
        description: "ดูหลักสูตรที่หน่วยงานของตนหรือหน่วยงานย่อยเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::ACADEMIC_CURRICULUM_READ_ORGANIZATION_UNIT,
        name: "ดูหลักสูตรของหน่วยงาน",
        module: "academic_curriculum",
        action: "read",
        scope: "organization_unit",
        description: "ดูหลักสูตรที่หน่วยงานของตนเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::ACADEMIC_CURRICULUM_READ_SCHOOL,
        name: "ดูหลักสูตรทั้งโรงเรียน",
        module: "academic_curriculum",
        action: "read",
        scope: "school",
        description: "ดูหลักสูตรทั้งหมดของโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_EXAM_SCHEDULE_MANAGE_SCHOOL,
        name: "จัดการตารางสอบวิชาการ",
        module: "academic_exam_schedule",
        action: "manage",
        scope: "school",
        description: "Create and manage academic exam schedules for the school",
    },
    PermissionDef {
        code: codes::ACADEMIC_EXAM_SCHEDULE_PUBLISH_SCHOOL,
        name: "ประกาศตารางสอบวิชาการ",
        module: "academic_exam_schedule",
        action: "publish",
        scope: "school",
        description: "Publish academic exam schedules for the school",
    },
    PermissionDef {
        code: codes::ACADEMIC_EXAM_SCHEDULE_READ_SCHOOL,
        name: "ดูตารางสอบวิชาการทั้งโรงเรียน",
        module: "academic_exam_schedule",
        action: "read",
        scope: "school",
        description: "Read academic exam schedules for the school",
    },
    PermissionDef {
        code: codes::ACADEMIC_QUESTION_BANK_MANAGE_ASSIGNED,
        name: "จัดการคลังข้อสอบที่รับผิดชอบ",
        module: "academic_question_bank",
        action: "manage",
        scope: "assigned",
        description: "สร้างและแก้ไขข้อสอบของตนเอง",
    },
    PermissionDef {
        code: codes::ACADEMIC_QUESTION_BANK_MANAGE_ORGANIZATION_UNIT,
        name: "จัดการคลังข้อสอบในกลุ่มสาระ",
        module: "academic_question_bank",
        action: "manage",
        scope: "organization_unit",
        description: "สร้างและแก้ไขข้อสอบของรายวิชาในกลุ่มสาระเดียวกัน",
    },
    PermissionDef {
        code: codes::ACADEMIC_QUESTION_BANK_MANAGE_SCHOOL,
        name: "จัดการคลังข้อสอบทั้งโรงเรียน",
        module: "academic_question_bank",
        action: "manage",
        scope: "school",
        description: "สร้าง แก้ไข และลบข้อสอบในคลังข้อสอบทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_QUESTION_BANK_READ_ASSIGNED,
        name: "ดูคลังข้อสอบที่รับผิดชอบ",
        module: "academic_question_bank",
        action: "read",
        scope: "assigned",
        description: "ดูข้อสอบที่ตนเองสร้างหรือเกี่ยวข้องกับรายวิชาที่รับผิดชอบ",
    },
    PermissionDef {
        code: codes::ACADEMIC_QUESTION_BANK_READ_ORGANIZATION_UNIT,
        name: "ดูคลังข้อสอบในกลุ่มสาระ",
        module: "academic_question_bank",
        action: "read",
        scope: "organization_unit",
        description: "ดูข้อสอบของรายวิชาในกลุ่มสาระเดียวกัน",
    },
    PermissionDef {
        code: codes::ACADEMIC_QUESTION_BANK_READ_SCHOOL,
        name: "ดูคลังข้อสอบทั้งโรงเรียน",
        module: "academic_question_bank",
        action: "read",
        scope: "school",
        description: "ดูข้อสอบในคลังข้อสอบทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_TERM_MANAGE_SCHOOL,
        name: "จัดการภาคเรียน",
        module: "academic_term",
        action: "manage",
        scope: "school",
        description: "สร้างและแก้ไขภาคเรียนที่ยังอยู่ระหว่างวางแผน",
    },
    PermissionDef {
        code: codes::ACADEMIC_TERM_READ_SCHOOL,
        name: "ดูภาคเรียน",
        module: "academic_term",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลภาคเรียนของโรงเรียน",
    },
    PermissionDef {
        code: codes::ACADEMIC_TIMETABLE_TODAY_READ_SCHOOL,
        name: "ดูตารางสอนวันนี้ทั้งโรงเรียน",
        module: "academic_timetable_today",
        action: "read",
        scope: "school",
        description: "ดูภาพรวมตารางสอนรายวันของครูทั้งโรงเรียนแบบอ่านอย่างเดียว",
    },
    PermissionDef {
        code: codes::ACADEMIC_YEAR_MANAGE_SCHOOL,
        name: "จัดการปีการศึกษา",
        module: "academic_year",
        action: "manage",
        scope: "school",
        description: "สร้างและแก้ไขปีการศึกษาที่ยังอยู่ระหว่างวางแผน",
    },
    PermissionDef {
        code: codes::ACADEMIC_YEAR_READ_SCHOOL,
        name: "ดูปีการศึกษา",
        module: "academic_year",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลปีการศึกษาของโรงเรียน",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_CREATE_ALL,
        name: "เพิ่มผลงานให้ผู้อื่น",
        module: "achievement",
        action: "create",
        scope: "all",
        description: "บันทึกผลงานแทนบุคคลากรอื่น",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_CREATE_OWN,
        name: "เพิ่มผลงานตนเอง",
        module: "achievement",
        action: "create",
        scope: "own",
        description: "บันทึกผลงานของตนเอง",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_DELETE_ALL,
        name: "ลบผลงานผู้อื่น",
        module: "achievement",
        action: "delete",
        scope: "all",
        description: "ลบผลงานของบุคคลากรอื่น",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_DELETE_OWN,
        name: "ลบผลงานตนเอง",
        module: "achievement",
        action: "delete",
        scope: "own",
        description: "ลบผลงานของตนเอง",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_READ_ALL,
        name: "ดูผลงานทั้งหมด",
        module: "achievement",
        action: "read",
        scope: "all",
        description: "ดูรายการผลงานของบุคคลากรทั้งหมด",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_READ_OWN,
        name: "ดูผลงานตนเอง",
        module: "achievement",
        action: "read",
        scope: "own",
        description: "ดูรายการผลงานของตนเอง",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_UPDATE_ALL,
        name: "แก้ไขผลงานผู้อื่น",
        module: "achievement",
        action: "update",
        scope: "all",
        description: "แก้ไขผลงานของบุคคลากรอื่น",
    },
    PermissionDef {
        code: codes::ACHIEVEMENT_UPDATE_OWN,
        name: "แก้ไขผลงานตนเอง",
        module: "achievement",
        action: "update",
        scope: "own",
        description: "แก้ไขผลงานของตนเอง",
    },
    PermissionDef {
        code: codes::ADMISSION_ENROLL_ALL,
        name: "รับมอบตัว",
        module: "admission",
        action: "enroll",
        scope: "all",
        description: "รับมอบตัวและสร้าง account นักเรียนในระบบ",
    },
    PermissionDef {
        code: codes::ADMISSION_MANAGE_ALL,
        name: "จัดการรับสมัคร",
        module: "admission",
        action: "manage",
        scope: "all",
        description: "สร้าง/แก้ไข รอบรับสมัคร, สายการเรียน, วิชาสอบ",
    },
    PermissionDef {
        code: codes::ADMISSION_READ_ALL,
        name: "ดูข้อมูลรับสมัคร",
        module: "admission",
        action: "read",
        scope: "all",
        description: "ดูรายชื่อผู้สมัคร, ผล, คะแนน",
    },
    PermissionDef {
        code: codes::ADMISSION_SCORES_ALL,
        name: "กรอกคะแนนและจัดห้อง",
        module: "admission",
        action: "scores",
        scope: "all",
        description: "กรอกคะแนนสอบ, เรียงคะแนน, จัดห้องเรียน",
    },
    PermissionDef {
        code: codes::ADMISSION_VERIFY_ALL,
        name: "ตรวจสอบใบสมัคร",
        module: "admission",
        action: "verify",
        scope: "all",
        description: "ยืนยัน/ปฏิเสธใบสมัครของผู้สมัคร",
    },
    PermissionDef {
        code: codes::CALENDAR_MANAGE_SCHOOL,
        name: "จัดการปฏิทินโรงเรียน",
        module: "calendar",
        action: "manage",
        scope: "school",
        description: "สร้าง แก้ไข ลบ หมวดหมู่ กลุ่มผู้เห็น และการแจ้งเตือนของปฏิทินโรงเรียน",
    },
    PermissionDef {
        code: codes::CALENDAR_READ_SCHOOL,
        name: "ดูปฏิทินโรงเรียน",
        module: "calendar",
        action: "read",
        scope: "school",
        description: "ดูปฏิทินและกำหนดการของโรงเรียน",
    },
    PermissionDef {
        code: codes::CERTIFICATE_CREATE_ORGANIZATION_UNIT,
        name: "สร้างโครงการเกียรติบัตรในหน่วยงาน",
        module: "certificate",
        action: "create",
        scope: "organization_unit",
        description: "สร้างโครงการ แบบ และรายชื่อผู้รับในหน่วยงานที่ได้รับสิทธิ์โดยตรง",
    },
    PermissionDef {
        code: codes::CERTIFICATE_CREATE_SCHOOL,
        name: "สร้างโครงการเกียรติบัตรระดับโรงเรียน",
        module: "certificate",
        action: "create",
        scope: "school",
        description: "สร้างโครงการ แบบ และรายชื่อผู้รับในขอบเขตทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::CERTIFICATE_DELETE_ORGANIZATION_UNIT,
        name: "ลบกิจกรรมเกียรติบัตรถาวรในหน่วยงาน",
        module: "certificate",
        action: "delete",
        scope: "organization_unit",
        description: "ลบกิจกรรม แบบ รายชื่อ คำขอ เกียรติบัตร และไฟล์ของหน่วยงานที่ได้รับสิทธิ์โดยตรงแบบถาวร",
    },
    PermissionDef {
        code: codes::CERTIFICATE_DELETE_SCHOOL,
        name: "ลบกิจกรรมเกียรติบัตรถาวรทั้งโรงเรียน",
        module: "certificate",
        action: "delete",
        scope: "school",
        description: "ลบกิจกรรม แบบ รายชื่อ คำขอ เกียรติบัตร และไฟล์ในขอบเขตทั้งโรงเรียนแบบถาวร",
    },
    PermissionDef {
        code: codes::CERTIFICATE_DOWNLOAD_ORGANIZATION_UNIT,
        name: "ดาวน์โหลดเกียรติบัตรในหน่วยงาน",
        module: "certificate",
        action: "download",
        scope: "organization_unit",
        description: "สร้างและดาวน์โหลดไฟล์เกียรติบัตรของหน่วยงานที่ได้รับสิทธิ์โดยตรง",
    },
    PermissionDef {
        code: codes::CERTIFICATE_DOWNLOAD_SCHOOL,
        name: "ดาวน์โหลดเกียรติบัตรทั้งโรงเรียน",
        module: "certificate",
        action: "download",
        scope: "school",
        description: "สร้างและดาวน์โหลดไฟล์เกียรติบัตรในขอบเขตทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::CERTIFICATE_ISSUE_SCHOOL,
        name: "ออกเลขเกียรติบัตรทั้งโรงเรียน",
        module: "certificate",
        action: "issue",
        scope: "school",
        description: "ตรวจสอบคำขอและออกเลขเกียรติบัตรแบบเรียงลำดับภายในธุรกรรม",
    },
    PermissionDef {
        code: codes::CERTIFICATE_READ_ORGANIZATION_UNIT,
        name: "ดูเกียรติบัตรในหน่วยงาน",
        module: "certificate",
        action: "read",
        scope: "organization_unit",
        description: "ดูโครงการ แบบ และรายชื่อผู้รับของหน่วยงานที่ได้รับสิทธิ์โดยตรง",
    },
    PermissionDef {
        code: codes::CERTIFICATE_READ_OWN,
        name: "ดูเกียรติบัตรของตนเอง",
        module: "certificate",
        action: "read",
        scope: "own",
        description: "ดูเกียรติบัตรที่เชื่อมกับบัญชีของตนเอง",
    },
    PermissionDef {
        code: codes::CERTIFICATE_READ_SCHOOL,
        name: "ดูเกียรติบัตรทั้งโรงเรียน",
        module: "certificate",
        action: "read",
        scope: "school",
        description: "ดูโครงการ คำขอออก และเกียรติบัตรทั้งหมดของโรงเรียน",
    },
    PermissionDef {
        code: codes::CERTIFICATE_REVOKE_SCHOOL,
        name: "เพิกถอนเกียรติบัตรทั้งโรงเรียน",
        module: "certificate",
        action: "revoke",
        scope: "school",
        description: "เพิกถอนเกียรติบัตรที่ออกแล้วโดยเก็บประวัติและเหตุผลไว้",
    },
    PermissionDef {
        code: codes::CERTIFICATE_SUBMIT_ORGANIZATION_UNIT,
        name: "ส่งคำขอออกเกียรติบัตรของหน่วยงาน",
        module: "certificate",
        action: "submit",
        scope: "organization_unit",
        description: "ส่งรายชื่อที่พร้อมแล้วให้ผู้มีสิทธิ์ระดับโรงเรียนตรวจสอบและออกเลข",
    },
    PermissionDef {
        code: codes::CERTIFICATE_SUBMIT_SCHOOL,
        name: "ส่งคำขอออกเกียรติบัตรระดับโรงเรียน",
        module: "certificate",
        action: "submit",
        scope: "school",
        description: "ส่งรายชื่อระดับโรงเรียนเข้าสู่กระบวนการตรวจสอบและออกเลข",
    },
    PermissionDef {
        code: codes::CERTIFICATE_UPDATE_ORGANIZATION_UNIT,
        name: "แก้ไขเกียรติบัตรในหน่วยงาน",
        module: "certificate",
        action: "update",
        scope: "organization_unit",
        description: "แก้ไขโครงการ แบบ และรายชื่อผู้รับของหน่วยงานที่ได้รับสิทธิ์โดยตรง",
    },
    PermissionDef {
        code: codes::CERTIFICATE_UPDATE_SCHOOL,
        name: "แก้ไขเกียรติบัตรทั้งโรงเรียน",
        module: "certificate",
        action: "update",
        scope: "school",
        description: "แก้ไขโครงการ แบบ และรายชื่อผู้รับในขอบเขตทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::DASHBOARD_READ_OWN,
        name: "แดชบอร์ด",
        module: "dashboard",
        action: "read",
        scope: "own",
        description: "ดูหน้าแดชบอร์ด",
    },
    PermissionDef {
        code: codes::FACILITY_CREATE_ALL,
        name: "สร้างอาคารสถานที่",
        module: "facility",
        action: "create",
        scope: "all",
        description: "เพิ่มข้อมูลอาคารและห้องใหม่",
    },
    PermissionDef {
        code: codes::FACILITY_DELETE_ALL,
        name: "ลบอาคารสถานที่",
        module: "facility",
        action: "delete",
        scope: "all",
        description: "ลบข้อมูลอาคารและห้อง",
    },
    PermissionDef {
        code: codes::FACILITY_READ_ALL,
        name: "ดูข้อมูลอาคารสถานที่",
        module: "facility",
        action: "read",
        scope: "all",
        description: "ดูรายชื่ออาคารและห้อง",
    },
    PermissionDef {
        code: codes::FACILITY_UPDATE_ALL,
        name: "แก้ไขอาคารสถานที่",
        module: "facility",
        action: "update",
        scope: "all",
        description: "แก้ไขข้อมูลอาคารและห้อง",
    },
    PermissionDef {
        code: codes::FEATURES_READ_ALL,
        name: "ดูฟีเจอร์",
        module: "features",
        action: "read",
        scope: "all",
        description: "ดูการตั้งค่าฟีเจอร์",
    },
    PermissionDef {
        code: codes::FEATURES_UPDATE_ALL,
        name: "แก้ไขฟีเจอร์",
        module: "features",
        action: "update",
        scope: "all",
        description: "แก้ไขการตั้งค่าฟีเจอร์",
    },
    PermissionDef {
        code: codes::FONT_MANAGE_SCHOOL,
        name: "จัดการคลังฟอนต์โรงเรียน",
        module: "font",
        action: "manage",
        scope: "school",
        description: "ดู อัปโหลด และลบฟอนต์กลางของโรงเรียนโดยไม่ให้สิทธิ์แก้ไขระบบที่นำฟอนต์ไปใช้",
    },
    PermissionDef {
        code: codes::HOMEROOM_MANAGE_SCHOOL,
        name: "จัดการห้องประจำชั้น",
        module: "homeroom",
        action: "manage",
        scope: "school",
        description: "สร้างและแก้ไขห้องประจำชั้นของโรงเรียน",
    },
    PermissionDef {
        code: codes::HOMEROOM_READ_SCHOOL,
        name: "ดูห้องประจำชั้น",
        module: "homeroom",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลห้องประจำชั้นของโรงเรียน",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_MANAGE_ASSIGNED,
        name: "จัดการการเปิดสอนที่รับผิดชอบ",
        module: "learning_offering",
        action: "manage",
        scope: "assigned",
        description: "จัดการการเปิดสอนและกลุ่มเรียนที่ได้รับมอบหมาย",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_MANAGE_ORGANIZATION_TREE,
        name: "จัดการการเปิดสอนในสายงาน",
        module: "learning_offering",
        action: "manage",
        scope: "organization_tree",
        description: "จัดการการเปิดสอนที่หน่วยงานของตนหรือหน่วยงานย่อยเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_MANAGE_ORGANIZATION_UNIT,
        name: "จัดการการเปิดสอนของหน่วยงาน",
        module: "learning_offering",
        action: "manage",
        scope: "organization_unit",
        description: "จัดการการเปิดสอนที่หน่วยงานของตนเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_MANAGE_SCHOOL,
        name: "จัดการการเปิดสอนทั้งโรงเรียน",
        module: "learning_offering",
        action: "manage",
        scope: "school",
        description: "จัดการการเปิดสอนและกลุ่มเรียนทั้งหมดของโรงเรียน",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_READ_ASSIGNED,
        name: "ดูการเปิดสอนที่รับผิดชอบ",
        module: "learning_offering",
        action: "read",
        scope: "assigned",
        description: "ดูการเปิดสอนและกลุ่มเรียนที่ได้รับมอบหมายเป็นผู้สอน",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_READ_ORGANIZATION_TREE,
        name: "ดูการเปิดสอนในสายงาน",
        module: "learning_offering",
        action: "read",
        scope: "organization_tree",
        description: "ดูการเปิดสอนที่หน่วยงานของตนหรือหน่วยงานย่อยเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_READ_ORGANIZATION_UNIT,
        name: "ดูการเปิดสอนของหน่วยงาน",
        module: "learning_offering",
        action: "read",
        scope: "organization_unit",
        description: "ดูการเปิดสอนที่หน่วยงานของตนเป็นเจ้าของ",
    },
    PermissionDef {
        code: codes::LEARNING_OFFERING_READ_SCHOOL,
        name: "ดูการเปิดสอนทั้งโรงเรียน",
        module: "learning_offering",
        action: "read",
        scope: "school",
        description: "ดูการเปิดสอนและกลุ่มเรียนทั้งหมดของโรงเรียน",
    },
    PermissionDef {
        code: codes::MENU_CREATE_ALL,
        name: "สร้างเมนู",
        module: "menu",
        action: "create",
        scope: "all",
        description: "สร้างเมนูใหม่",
    },
    PermissionDef {
        code: codes::MENU_DELETE_ALL,
        name: "ลบเมนู",
        module: "menu",
        action: "delete",
        scope: "all",
        description: "ลบเมนู",
    },
    PermissionDef {
        code: codes::MENU_READ_ALL,
        name: "ดูเมนู",
        module: "menu",
        action: "read",
        scope: "all",
        description: "ดูเมนูทั้งหมด",
    },
    PermissionDef {
        code: codes::MENU_UPDATE_ALL,
        name: "แก้ไขเมนู",
        module: "menu",
        action: "update",
        scope: "all",
        description: "แก้ไขเมนู",
    },
    PermissionDef {
        code: codes::ORGANIZATION_WORK_APPROVE_ORGANIZATION_UNIT,
        name: "อนุมัติงานในหน่วยงาน",
        module: "organization_work",
        action: "approve",
        scope: "organization_unit",
        description: "อนุมัติหรือตรวจสอบงานของสมาชิกในหน่วยงาน",
    },
    PermissionDef {
        code: codes::ORGANIZATION_WORK_CREATE_OWN,
        name: "สร้าง/ส่งงาน",
        module: "organization_work",
        action: "create",
        scope: "own",
        description: "ส่งงานหรือสร้างบันทึกงานใหม่",
    },
    PermissionDef {
        code: codes::ORGANIZATION_WORK_READ_ORGANIZATION_UNIT,
        name: "ดูงานในหน่วยงาน",
        module: "organization_work",
        action: "read",
        scope: "organization_unit",
        description: "ดูรายการงานทั้งหมดในหน่วยงานที่สังกัด",
    },
    PermissionDef {
        code: codes::ORGANIZATION_WORK_READ_OWN,
        name: "ดูงานของตนเอง",
        module: "organization_work",
        action: "read",
        scope: "own",
        description: "ดูรายการงานที่ตนเองรับผิดชอบ",
    },
    PermissionDef {
        code: codes::ORGANIZATION_WORK_UPDATE_OWN,
        name: "แก้ไขงานตนเอง",
        module: "organization_work",
        action: "update",
        scope: "own",
        description: "แก้ไขรายละเอียดงานของตนเอง",
    },
    PermissionDef {
        code: codes::ROLES_ASSIGN_ALL,
        name: "มอบหมายบทบาท",
        module: "roles",
        action: "assign",
        scope: "all",
        description: "มอบหมายบทบาทให้ผู้ใช้",
    },
    PermissionDef {
        code: codes::ROLES_CREATE_ALL,
        name: "สร้างบทบาท",
        module: "roles",
        action: "create",
        scope: "all",
        description: "สร้างบทบาทและฝ่ายใหม่",
    },
    PermissionDef {
        code: codes::ROLES_DELETE_ALL,
        name: "ลบบทบาท",
        module: "roles",
        action: "delete",
        scope: "all",
        description: "ลบบทบาทและฝ่าย",
    },
    PermissionDef {
        code: codes::ROLES_READ_ALL,
        name: "ดูบทบาท",
        module: "roles",
        action: "read",
        scope: "all",
        description: "ดูข้อมูลบทบาทและฝ่ายทั้งหมด",
    },
    PermissionDef {
        code: codes::ROLES_REMOVE_ALL,
        name: "ถอนบทบาท",
        module: "roles",
        action: "remove",
        scope: "all",
        description: "ถอนบทบาทจากผู้ใช้",
    },
    PermissionDef {
        code: codes::ROLES_UPDATE_ALL,
        name: "แก้ไขบทบาท",
        module: "roles",
        action: "update",
        scope: "all",
        description: "แก้ไขบทบาทและฝ่าย",
    },
    PermissionDef {
        code: codes::SETTINGS_READ_ALL,
        name: "ดูการตั้งค่า",
        module: "settings",
        action: "read",
        scope: "all",
        description: "ดูการตั้งค่าระบบ",
    },
    PermissionDef {
        code: codes::SETTINGS_UPDATE_ALL,
        name: "แก้ไขการตั้งค่า",
        module: "settings",
        action: "update",
        scope: "all",
        description: "แก้ไขการตั้งค่าระบบ",
    },
    PermissionDef {
        code: codes::STAFF_CREATE_ALL,
        name: "เพิ่มบุคลากร",
        module: "staff",
        action: "create",
        scope: "all",
        description: "สร้างบุคลากรใหม่",
    },
    PermissionDef {
        code: codes::STAFF_DELETE_ALL,
        name: "ลบบุคลากร",
        module: "staff",
        action: "delete",
        scope: "all",
        description: "ลบบุคลากร",
    },
    PermissionDef {
        code: codes::STAFF_PII_READ_OWN,
        name: "ดูข้อมูลอ่อนไหวบุคลากรของตนเอง",
        module: "staff_pii",
        action: "read",
        scope: "own",
        description: "ดูข้อมูลอ่อนไหวของบุคลากรเฉพาะของตนเอง",
    },
    PermissionDef {
        code: codes::STAFF_PII_READ_SCHOOL,
        name: "ดูข้อมูลอ่อนไหวบุคลากรทั้งโรงเรียน",
        module: "staff_pii",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลอ่อนไหวของบุคลากรทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::STAFF_PROFILE_READ_ORGANIZATION_TREE,
        name: "ดูโปรไฟล์บุคลากรในสายงาน",
        module: "staff_profile",
        action: "read",
        scope: "organization_tree",
        description: "ดูข้อมูลโปรไฟล์บุคลากรในหน่วยงานของตนเองและหน่วยงานย่อย",
    },
    PermissionDef {
        code: codes::STAFF_PROFILE_READ_ORGANIZATION_UNIT,
        name: "ดูโปรไฟล์บุคลากรในหน่วยงาน",
        module: "staff_profile",
        action: "read",
        scope: "organization_unit",
        description: "ดูข้อมูลโปรไฟล์บุคลากรที่อยู่ในหน่วยงานเดียวกัน",
    },
    PermissionDef {
        code: codes::STAFF_PROFILE_READ_OWN,
        name: "ดูโปรไฟล์บุคลากรของตนเอง",
        module: "staff_profile",
        action: "read",
        scope: "own",
        description: "ดูข้อมูลโปรไฟล์บุคลากรของตนเอง",
    },
    PermissionDef {
        code: codes::STAFF_PROFILE_READ_SCHOOL,
        name: "ดูโปรไฟล์บุคลากรทั้งโรงเรียน",
        module: "staff_profile",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลโปรไฟล์บุคลากรทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::STAFF_READ_ALL,
        name: "ดูบุคลากรทั้งหมด",
        module: "staff",
        action: "read",
        scope: "all",
        description: "ดูข้อมูลบุคลากรทั้งหมด",
    },
    PermissionDef {
        code: codes::STAFF_UPDATE_ALL,
        name: "แก้ไขบุคลากร",
        module: "staff",
        action: "update",
        scope: "all",
        description: "แก้ไขข้อมูลบุคลากร",
    },
    PermissionDef {
        code: codes::STUDENT_ACADEMIC_YEAR_MANAGE_SCHOOL,
        name: "จัดการข้อมูลนักเรียนรายปี",
        module: "student_academic_year",
        action: "manage",
        scope: "school",
        description: "จัดการสถานะและการจัดห้องของนักเรียนในแต่ละปีการศึกษา",
    },
    PermissionDef {
        code: codes::STUDENT_ACADEMIC_YEAR_READ_SCHOOL,
        name: "ดูข้อมูลนักเรียนรายปี",
        module: "student_academic_year",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลสถานะและห้องประจำชั้นของนักเรียนในแต่ละปีการศึกษา",
    },
    PermissionDef {
        code: codes::STUDENT_CREATE_ALL,
        name: "เพิ่มนักเรียน",
        module: "student",
        action: "create",
        scope: "all",
        description: "สร้างนักเรียนใหม่",
    },
    PermissionDef {
        code: codes::STUDENT_DELETE_ALL,
        name: "ลบนักเรียน",
        module: "student",
        action: "delete",
        scope: "all",
        description: "ลบนักเรียน",
    },
    PermissionDef {
        code: codes::STUDENT_PII_READ_ASSIGNED,
        name: "ดูข้อมูลอ่อนไหวนักเรียนที่รับผิดชอบ",
        module: "student_pii",
        action: "read",
        scope: "assigned",
        description: "ดูข้อมูลอ่อนไหวของนักเรียนที่อยู่ในห้อง/งานที่ได้รับมอบหมาย",
    },
    PermissionDef {
        code: codes::STUDENT_PII_READ_OWN,
        name: "ดูข้อมูลอ่อนไหวนักเรียนของตนเอง",
        module: "student_pii",
        action: "read",
        scope: "own",
        description: "ดูข้อมูลอ่อนไหวของนักเรียนเฉพาะของตนเอง",
    },
    PermissionDef {
        code: codes::STUDENT_PII_READ_SCHOOL,
        name: "ดูข้อมูลอ่อนไหวนักเรียนทั้งโรงเรียน",
        module: "student_pii",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลอ่อนไหวของนักเรียนทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::STUDENT_READ_ASSIGNED,
        name: "ดูนักเรียนที่รับผิดชอบ",
        module: "student",
        action: "read",
        scope: "assigned",
        description: "ดูข้อมูลนักเรียนที่อยู่ในห้อง/งานที่ได้รับมอบหมาย",
    },
    PermissionDef {
        code: codes::STUDENT_READ_OWN,
        name: "ดูข้อมูลตนเอง",
        module: "student",
        action: "read",
        scope: "own",
        description: "นักเรียนดูข้อมูลตนเอง",
    },
    PermissionDef {
        code: codes::STUDENT_READ_SCHOOL,
        name: "ดูนักเรียนทั้งโรงเรียน",
        module: "student",
        action: "read",
        scope: "school",
        description: "ดูข้อมูลนักเรียนทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::STUDENT_UPDATE_ALL,
        name: "แก้ไขนักเรียน",
        module: "student",
        action: "update",
        scope: "all",
        description: "แก้ไขข้อมูลนักเรียนทั้งหมด",
    },
    PermissionDef {
        code: codes::STUDENT_UPDATE_OWN,
        name: "แก้ไขข้อมูลตนเอง",
        module: "student",
        action: "update",
        scope: "own",
        description: "นักเรียนแก้ไขข้อมูลตนเอง (จำกัดฟิลด์)",
    },
    PermissionDef {
        code: codes::SUPERVISION_APPROVE_SCHOOL,
        name: "อนุมัติผลนิเทศทั้งโรงเรียน",
        module: "supervision",
        action: "approve",
        scope: "school",
        description: "ตรวจสอบและอนุมัติผลนิเทศการสอนทั้งโรงเรียนก่อนให้ครูรับทราบผล",
    },
    PermissionDef {
        code: codes::SUPERVISION_EVALUATE_ASSIGNED,
        name: "ประเมินรายการนิเทศที่ได้รับมอบหมาย",
        module: "supervision",
        action: "evaluate",
        scope: "assigned",
        description: "กรอกและส่งผลประเมินรายการนิเทศที่ตนเองได้รับมอบหมาย",
    },
    PermissionDef {
        code: codes::SUPERVISION_MANAGE_ORGANIZATION_TREE,
        name: "จัดการนิเทศในสายงาน",
        module: "supervision",
        action: "manage",
        scope: "organization_tree",
        description: "อนุมัติคำขอและจัดการรายการนิเทศในหน่วยงานของตนเองและหน่วยงานย่อย",
    },
    PermissionDef {
        code: codes::SUPERVISION_MANAGE_ORGANIZATION_UNIT,
        name: "จัดการนิเทศในหน่วยงาน",
        module: "supervision",
        action: "manage",
        scope: "organization_unit",
        description: "อนุมัติคำขอและจัดการรายการนิเทศของบุคลากรในหน่วยงานเดียวกัน",
    },
    PermissionDef {
        code: codes::SUPERVISION_MANAGE_SCHOOL,
        name: "จัดการระบบนิเทศทั้งโรงเรียน",
        module: "supervision",
        action: "manage",
        scope: "school",
        description: "จัดการรอบนิเทศ แบบประเมิน เป้าหมาย คำขอ และผู้ประเมินทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::SUPERVISION_READ_ASSIGNED,
        name: "ดูรายการนิเทศที่ได้รับมอบหมาย",
        module: "supervision",
        action: "read",
        scope: "assigned",
        description: "ดูรายการนิเทศการสอนที่ได้รับมอบหมายให้ประเมิน",
    },
    PermissionDef {
        code: codes::SUPERVISION_READ_ORGANIZATION_TREE,
        name: "ดูนิเทศในสายงาน",
        module: "supervision",
        action: "read",
        scope: "organization_tree",
        description: "ดูรายการนิเทศการสอนในหน่วยงานของตนเองและหน่วยงานย่อย",
    },
    PermissionDef {
        code: codes::SUPERVISION_READ_ORGANIZATION_UNIT,
        name: "ดูนิเทศในหน่วยงาน",
        module: "supervision",
        action: "read",
        scope: "organization_unit",
        description: "ดูรายการนิเทศการสอนของบุคลากรในหน่วยงานเดียวกัน",
    },
    PermissionDef {
        code: codes::SUPERVISION_READ_OWN,
        name: "ดูผลนิเทศของตนเอง",
        module: "supervision",
        action: "read",
        scope: "own",
        description: "ดูรายการและผลนิเทศการสอนของตนเอง",
    },
    PermissionDef {
        code: codes::SUPERVISION_READ_SCHOOL,
        name: "ดูนิเทศทั้งโรงเรียน",
        module: "supervision",
        action: "read",
        scope: "school",
        description: "ดูรายการนิเทศการสอนและรายงานทั้งโรงเรียน",
    },
    PermissionDef {
        code: codes::SUPERVISION_REQUEST_OWN,
        name: "จองคาบนิเทศของตนเอง",
        module: "supervision",
        action: "request",
        scope: "own",
        description: "ส่งคำขอจองคาบเพื่อรับการนิเทศการสอนของตนเอง",
    },
];
