<script lang="ts">
	import { onMount } from 'svelte';
	import { SvelteSet } from 'svelte/reactivity';

	let { data } = $props();

	import {
		getAcademicStructure,
		listClassrooms,
		listClassroomCourses,
		removeCourse,
		updateCourse,
		generateCoursesFromPlan,
		assignCourses,
		listSubjects,
		listStudyPlanSubjects,
		listCourseInstructors,
		batchListCourseInstructors,
		addCourseInstructor,
		removeCourseInstructor,
		updateCourseInstructorRole,
		listClassroomActivities,
		removeClassroomFromSlot,
		ACTIVITY_TYPE_LABELS,
		type AcademicStructureData,
		type Classroom,
		type ClassroomCourse,
		type CourseInstructor,
		type ClassroomActivity,
		type Subject,
		type StudyPlanSubject
	} from '$lib/api/academic';
	import { lookupStaff, type StaffLookupItem } from '$lib/api/lookup';
	import { toast } from 'svelte-sonner';
	import * as Card from '$lib/components/ui/card';
	import * as Table from '$lib/components/ui/table';
	import { Button } from '$lib/components/ui/button';
	import { Badge } from '$lib/components/ui/badge';
	import { Label } from '$lib/components/ui/label';
	import * as Select from '$lib/components/ui/select';
	import * as Popover from '$lib/components/ui/popover';
	import * as Command from '$lib/components/ui/command';
	import * as Dialog from '$lib/components/ui/dialog';
	import * as Tabs from '$lib/components/ui/tabs';
	import { PageShell } from '$lib/components/app-layout';
	import { LoadingButton, PageSkeleton, PageState } from '$lib/components/app-state';
	import { PERMISSIONS } from '$lib/permissions/registry';
	import { can } from '$lib/stores/permissions';
	import {
		Loader2,
		Trash2,
		Calendar,
		Settings,
		Wand2,
		Plus,
		FileSpreadsheet,
		Check,
		ChevronsUpDown
	} from 'lucide-svelte';
	import {
		actualRowsForWorksheet,
		actualSubjectActivityReportForWorksheet,
		actualSummaryForWorksheet,
		buildActualSubjectActivityRows,
		buildActualCurriculumRows,
		summarizeActualCurriculum
	} from '$lib/utils/curriculum-export';

	type ClassroomActivityExportItem = ClassroomActivity & {
		classroom_id: string;
		semester_id: string;
	};

	const canReadCoursePlan = $derived($can.has(PERMISSIONS.ACADEMIC_COURSE_PLAN_READ_ALL));
	const canManageCoursePlan = $derived($can.has(PERMISSIONS.ACADEMIC_COURSE_PLAN_MANAGE_ALL));

	// State
	let loading = $state(true);
	let structure = $state<AcademicStructureData>({ years: [], semesters: [], levels: [] });

	// Filter Selections
	let selectedYearId = $state('');
	let selectedTermId = $state('');
	let selectedClassroomId = $state('');

	// Data
	let classrooms = $state<Classroom[]>([]);
	let courses = $state<ClassroomCourse[]>([]);
	let classroomActivities = $state<ClassroomActivity[]>([]);
	let loadingActivities = $state(false);

	// Edit Dialog
	let showEditDialog = $state(false);
	let editingCourse = $state<ClassroomCourse | null>(null);
	let deletingCourse = $state<ClassroomCourse | null>(null);
	let showDeleteDialog = $state(false);
	let submitting = $state(false);
	let teachers = $state<StaffLookupItem[]>([]);
	let selectedTeacherId = $state<string>('');
	let editTeacherPickerOpen = $state(false);
	let teachersLoaded = $state(false);

	// Auto-generate states
	let showAutoGenerateDialog = $state(false);
	let autoGenerating = $state(false);
	let showActualExportDialog = $state(false);
	let actualExportYearId = $state('');
	let exportingActualCurriculum = $state(false);

	// Add course (manual) states
	let showAddCourseDialog = $state(false);
	let addCourseTab = $state<'plan' | 'catalog'>('plan');
	let addCourseLoading = $state(false);
	let addCourseSaving = $state<string>(''); // subject_id currently being added
	let planSubjectsForAdd = $state<StudyPlanSubject[]>([]);
	let catalogSubjectsForAdd = $state<Subject[]>([]);

	// Team teaching states
	let teamInstructorsMap = $state<Record<string, CourseInstructor[]>>({});
	let showTeamDialog = $state(false);
	let teamDialogCourseId = $state('');
	let teamDialogSelectedInstructor = $state('');
	let teamDialogRole = $state<'primary' | 'secondary'>('secondary');
	let teamTeacherPickerOpen = $state(false);
	let teamInstructorAdding = $state(false);

	function teacherName(teacherId: string) {
		return teachers.find((teacher) => teacher.id === teacherId)?.name ?? '';
	}

	async function loadTeamInstructors(courseId: string) {
		if (!canReadCoursePlan) return;

		try {
			const res = await listCourseInstructors(courseId);
			teamInstructorsMap[courseId] = res.data ?? [];
			teamInstructorsMap = { ...teamInstructorsMap };
		} catch {
			/* ignore */
		}
	}

	async function openTeamDialog(courseId: string) {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์จัดการทีมครูผู้สอน');
			return;
		}

		teamDialogCourseId = courseId;
		teamDialogSelectedInstructor = '';
		teamDialogRole = 'secondary';
		teamTeacherPickerOpen = false;
		if (!teachersLoaded) await loadTeachers();
		showTeamDialog = true;
		loadTeamInstructors(courseId);
	}

	async function handleAddTeamInstructor() {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์จัดการทีมครูผู้สอน');
			return;
		}

		if (!teamDialogSelectedInstructor) return;
		teamInstructorAdding = true;
		try {
			await addCourseInstructor(teamDialogCourseId, teamDialogSelectedInstructor, teamDialogRole);
			await loadTeamInstructors(teamDialogCourseId);
			await fetchCourses();
			teamDialogSelectedInstructor = '';
			teamTeacherPickerOpen = false;
			toast.success('เพิ่มครูแล้ว');
		} catch {
			toast.error('เกิดข้อผิดพลาด');
		} finally {
			teamInstructorAdding = false;
		}
	}

	async function handleRemoveTeamInstructor(courseId: string, userId: string) {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์จัดการทีมครูผู้สอน');
			return;
		}

		try {
			await removeCourseInstructor(courseId, userId);
			await loadTeamInstructors(courseId);
			await fetchCourses();
			toast.success('ลบครูแล้ว');
		} catch {
			toast.error('เกิดข้อผิดพลาด');
		}
	}

	async function handlePromoteToPrimary(courseId: string, userId: string) {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์จัดการทีมครูผู้สอน');
			return;
		}

		try {
			await updateCourseInstructorRole(courseId, userId, 'primary');
			await loadTeamInstructors(courseId);
			await fetchCourses();
			toast.success('เปลี่ยนเป็นครูหลักแล้ว');
		} catch {
			toast.error('เกิดข้อผิดพลาด');
		}
	}

	// Derived
	let filteredSemesters = $derived(
		structure.semesters.filter((s) => s.academic_year_id === selectedYearId)
	);

	let currentClassroom = $derived(classrooms.find((c) => c.id === selectedClassroomId));

	// Summary Statistics
	let summaryStats = $derived.by(() => {
		// ใช้ subject.hours_per_semester จริงจากคลังวิชา (ไม่ประมาณจาก credit)
		let basicCredit = 0;
		let basicHours = 0;
		let additionalCredit = 0;
		let additionalHours = 0;

		courses.forEach((c) => {
			const credit = c.subject_credit ?? 0;
			const hours = c.subject_hours ?? 0;

			if (c.subject_type === 'BASIC') {
				basicCredit += credit;
				basicHours += hours;
			} else if (c.subject_type === 'ADDITIONAL') {
				additionalCredit += credit;
				additionalHours += hours;
			}
			// ACTIVITY subject_type ไม่รวมกับวิชา — กิจกรรมพัฒนาผู้เรียนใช้ classroomActivities แยก
		});

		// กิจกรรมพัฒนาผู้เรียน: นับจำนวน + รวมคาบ/สัปดาห์
		const activityCount = classroomActivities.length;
		const activityPeriodsPerWeek = classroomActivities.reduce(
			(sum, a) => sum + (a.periods_per_week ?? 0),
			0
		);

		return {
			basic: { credit: basicCredit, hours: basicHours },
			additional: { credit: additionalCredit, hours: additionalHours },
			activity: { count: activityCount, periods: activityPeriodsPerWeek },
			total: {
				credit: basicCredit + additionalCredit,
				hours: basicHours + additionalHours
			}
		};
	});

	// Sorted courses: Basic -> Additional -> Activity -> Others
	let sortedCourses = $derived(
		[...courses].sort((a, b) => {
			const typeOrder: Record<string, number> = { BASIC: 1, ADDITIONAL: 2, ACTIVITY: 3 };
			const orderA = typeOrder[a.subject_type || ''] || 4;
			const orderB = typeOrder[b.subject_type || ''] || 4;

			if (orderA !== orderB) return orderA - orderB;
			return (a.subject_code || '').localeCompare(b.subject_code || '');
		})
	);

	// Effects / Loaders
	async function initData() {
		if (!canReadCoursePlan) {
			structure = { years: [], semesters: [], levels: [] };
			classrooms = [];
			courses = [];
			classroomActivities = [];
			loading = false;
			return;
		}

		try {
			loading = true;
			const res = await getAcademicStructure();
			structure = res.data;

			// Default Year
			const activeYear = structure.years.find((y) => y.is_active) || structure.years[0];
			if (activeYear) {
				selectedYearId = activeYear.id;
				actualExportYearId = activeYear.id;
				await fetchClassrooms();
				await fetchClassrooms();
			}
			if (canManageCoursePlan) loadTeachers(); // Preload teachers for management flows
		} catch (e) {
			console.error(e);
			toast.error('โหลดข้อมูลตั้งต้นไม่สำเร็จ');
		} finally {
			loading = false;
		}
	}

	function openActualExportDialog() {
		if (!canReadCoursePlan) {
			toast.error('ไม่มีสิทธิ์ส่งออกข้อมูลใช้จริง');
			return;
		}

		actualExportYearId =
			actualExportYearId ||
			selectedYearId ||
			structure.years.find((year) => year.is_active)?.id ||
			'';
		showActualExportDialog = true;
	}

	async function handleExportActualCurriculum() {
		if (!canReadCoursePlan) {
			toast.error('ไม่มีสิทธิ์ส่งออกข้อมูลใช้จริง');
			return;
		}

		if (!actualExportYearId) {
			toast.error('กรุณาเลือกปีการศึกษา');
			return;
		}

		exportingActualCurriculum = true;
		try {
			const exportYear = structure.years.find((year) => year.id === actualExportYearId);
			const exportSemesters = structure.semesters.filter(
				(semester) => semester.academic_year_id === actualExportYearId
			);
			if (!exportYear || exportSemesters.length === 0) {
				toast.error('ไม่พบภาคเรียนในปีการศึกษาที่เลือก');
				return;
			}

			const exportClassrooms = (await listClassrooms({ year_id: actualExportYearId })).data ?? [];
			const courseGroups = await Promise.all(
				exportSemesters.map((semester) =>
					listClassroomCourses({ semesterId: semester.id }).then((res) => res.data ?? [])
				)
			);
			const exportCourses = courseGroups.flat();
			const courseInstructorsByCourseId = await batchListCourseInstructors(
				exportCourses.map((course) => course.id)
			).then((res) => res.data ?? {});
			const activityGroups = await Promise.all(
				exportClassrooms.flatMap((classroom) =>
					exportSemesters.map((semester) =>
						listClassroomActivities(classroom.id, semester.id).then((res) =>
							(res.data ?? []).map((activity) => ({
								...activity,
								classroom_id: classroom.id,
								semester_id: semester.id
							}))
						)
					)
				)
			);

			const rows = buildActualCurriculumRows({
				yearName: exportYear.name,
				semesters: exportSemesters,
				classrooms: exportClassrooms,
				courses: exportCourses,
				activities: activityGroups.flat() as ClassroomActivityExportItem[]
			});
			const subjectActivityRows = buildActualSubjectActivityRows({
				yearName: exportYear.name,
				semesters: exportSemesters,
				classrooms: exportClassrooms,
				courses: exportCourses,
				activities: activityGroups.flat() as ClassroomActivityExportItem[],
				courseInstructorsByCourseId
			});
			const summaryRows = summarizeActualCurriculum(rows);

			const XLSX = await import('xlsx');
			const workbook = XLSX.utils.book_new();
			XLSX.utils.book_append_sheet(
				workbook,
				XLSX.utils.json_to_sheet(actualRowsForWorksheet(rows)),
				'ใช้จริง'
			);
			const subjectActivityWorksheet = XLSX.utils.aoa_to_sheet(
				actualSubjectActivityReportForWorksheet(subjectActivityRows)
			);
			subjectActivityWorksheet['!cols'] = [
				{ wch: 14 },
				{ wch: 32 },
				{ wch: 14 },
				{ wch: 8 },
				{ wch: 8 },
				{ wch: 54 },
				{ wch: 42 }
			];
			XLSX.utils.book_append_sheet(workbook, subjectActivityWorksheet, 'รายวิชา-กิจกรรม');
			XLSX.utils.book_append_sheet(
				workbook,
				XLSX.utils.json_to_sheet(actualSummaryForWorksheet(summaryRows)),
				'สรุปห้องเรียน'
			);
			XLSX.writeFile(workbook, `รายวิชาที่ใช้จริง-${exportYear.name}.xlsx`);
			toast.success(`ส่งออกข้อมูลใช้จริง ${rows.length} รายการแล้ว`);
			showActualExportDialog = false;
		} catch (e) {
			console.error(e);
			toast.error('ส่งออกข้อมูลใช้จริงไม่สำเร็จ');
		} finally {
			exportingActualCurriculum = false;
		}
	}

	async function fetchClassrooms() {
		if (!canReadCoursePlan || !selectedYearId) return;
		try {
			const res = await listClassrooms({ year_id: selectedYearId });
			classrooms = res.data;
			selectedClassroomId = ''; // Reset class when year changes
		} catch (e) {
			console.error(e);
			toast.error('โหลดห้องเรียนไม่สำเร็จ');
		}
	}

	async function fetchCourses() {
		if (!canReadCoursePlan || !selectedClassroomId || !selectedTermId) return;
		try {
			loading = true;
			const res = await listClassroomCourses(selectedClassroomId, selectedTermId);
			courses = res.data;
		} catch (e) {
			console.error(e);
			toast.error('โหลดข้อมูลรายวิชาไม่สำเร็จ');
		} finally {
			loading = false;
		}
	}

	async function fetchClassroomActivities() {
		if (!canReadCoursePlan) return;

		if (!selectedClassroomId || !selectedTermId) {
			classroomActivities = [];
			return;
		}
		try {
			loadingActivities = true;
			const res = await listClassroomActivities(selectedClassroomId, selectedTermId);
			classroomActivities = res.data ?? [];
		} catch (e) {
			console.error(e);
			classroomActivities = [];
		} finally {
			loadingActivities = false;
		}
	}

	async function handleRemoveClassroomActivity(activity: ClassroomActivity) {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์ลบกิจกรรมออกจากห้องเรียน');
			return;
		}

		if (!selectedClassroomId) return;
		try {
			await removeClassroomFromSlot(selectedClassroomId, activity.slot_id);
			toast.success('ลบแล้ว — ถ้าเป็นห้องสุดท้าย slot จะหายด้วย');
			await fetchClassroomActivities();
		} catch (e) {
			console.error(e);
			toast.error('ลบไม่สำเร็จ');
		}
	}

	function openDeleteDialog(course: ClassroomCourse) {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์ลบวิชาออกจากห้องเรียน');
			return;
		}

		deletingCourse = course;
		showDeleteDialog = true;
	}

	async function handleRemove() {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์ลบวิชาออกจากห้องเรียน');
			return;
		}

		if (!deletingCourse) return;

		submitting = true;
		try {
			await removeCourse(deletingCourse.id);
			toast.success('ลบวิชาสำเร็จ');
			showDeleteDialog = false;
			await fetchCourses();
		} catch (e) {
			console.error(e);
			toast.error('ลบไม่สำเร็จ');
		} finally {
			submitting = false;
		}
	}

	// Auto-Generate Courses from Study Plan
	async function handleAutoGenerate() {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์สร้างรายวิชาอัตโนมัติ');
			return;
		}

		if (!selectedClassroomId || !selectedTermId || !currentClassroom) {
			toast.error('กรุณาเลือกห้องเรียนและภาคเรียน');
			return;
		}

		autoGenerating = true;
		try {
			const result = await generateCoursesFromPlan({
				classroom_id: selectedClassroomId,
				academic_semester_id: selectedTermId,
				skip_existing: true
			});

			showAutoGenerateDialog = false;
			const coursesAdded = result.courses_created ?? result.items.added_count;
			const activitiesAdded = result.activities_created;
			toast.success(`สร้างคอร์ส ${coursesAdded} + กิจกรรม ${activitiesAdded}`, {
				duration: 5000
			});

			await fetchCourses();
			await fetchClassroomActivities();
		} catch (e) {
			console.error(e);
			toast.error('สร้างรายวิชาอัตโนมัติไม่สำเร็จ: ' + (e instanceof Error ? e.message : ''));
		} finally {
			autoGenerating = false;
		}
	}

	async function openAddCourseDialog() {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์เพิ่มรายวิชา');
			return;
		}

		if (!selectedClassroomId || !selectedTermId || !currentClassroom) {
			toast.error('กรุณาเลือกห้องเรียนและภาคเรียน');
			return;
		}
		addCourseTab = currentClassroom.study_plan_version_id ? 'plan' : 'catalog';
		showAddCourseDialog = true;
		await loadAddCourseLists();
	}

	async function loadAddCourseLists() {
		if (!canManageCoursePlan) return;

		if (!currentClassroom || !selectedTermId || !selectedYearId) return;
		addCourseLoading = true;
		try {
			const semester = structure.semesters.find((s) => s.id === selectedTermId);
			const termStr = semester?.term ?? '';

			const promises: Promise<void>[] = [];

			// จาก plan — เฉพาะถ้าห้องผูก plan ไว้
			if (currentClassroom.study_plan_version_id && currentClassroom.grade_level_id && termStr) {
				promises.push(
					listStudyPlanSubjects({
						study_plan_version_id: currentClassroom.study_plan_version_id,
						grade_level_id: currentClassroom.grade_level_id,
						term: termStr
					}).then((res) => {
						planSubjectsForAdd = res.data;
					})
				);
			} else {
				planSubjectsForAdd = [];
			}

			// จากคลัง — ทั้งหมดที่ active ในปีนี้
			promises.push(
				listSubjects({
					active_only: true,
					active_in_year_id: selectedYearId
				}).then((res) => {
					catalogSubjectsForAdd = res.data ?? [];
				})
			);

			await Promise.all(promises);
		} catch (e) {
			console.error(e);
			toast.error('โหลดรายวิชาไม่สำเร็จ');
		} finally {
			addCourseLoading = false;
		}
	}

	async function handleAddCourse(subjectId: string) {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์เพิ่มรายวิชา');
			return;
		}

		if (!selectedClassroomId || !selectedTermId) return;
		addCourseSaving = subjectId;
		try {
			await assignCourses({
				classroom_id: selectedClassroomId,
				academic_semester_id: selectedTermId,
				subject_ids: [subjectId]
			});
			toast.success('เพิ่มรายวิชาแล้ว');
			await fetchCourses();
		} catch (e) {
			console.error(e);
			toast.error('เพิ่มไม่สำเร็จ');
		} finally {
			addCourseSaving = '';
		}
	}

	async function loadTeachers() {
		if (!canManageCoursePlan) return;

		if (teachersLoaded) return;
		try {
			const res = await lookupStaff({ activeOnly: true, limit: 1000 });
			teachers = res;
			teachersLoaded = true;
		} catch (e) {
			console.error('Failed to load teachers', e);
		}
	}

	async function openEditDialog(course: ClassroomCourse) {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์แก้ไขรายวิชา');
			return;
		}

		editingCourse = course;
		selectedTeacherId = course.primary_instructor_id || 'unassigned';
		editTeacherPickerOpen = false;
		if (!teachersLoaded) await loadTeachers();
		showEditDialog = true;
	}

	async function handleUpdateCourse() {
		if (!canManageCoursePlan) {
			toast.error('ไม่มีสิทธิ์แก้ไขรายวิชา');
			return;
		}

		if (!editingCourse) return;
		submitting = true;
		try {
			const teacherId = selectedTeacherId === 'unassigned' ? null : selectedTeacherId;
			await updateCourse(editingCourse.id, {
				primary_instructor_id: teacherId
			});
			toast.success('บันทึกข้อมูลสำเร็จ');
			showEditDialog = false;
			await fetchCourses();
		} catch (e) {
			console.error(e);
			toast.error('อัปเดตข้อมูลไม่สำเร็จ');
		} finally {
			submitting = false;
		}
	}

	// Watchers (Svelte 5 effects or just bind:value + handler)
	// Using handlers on Select.onValueChange is better for explicit control?
	// But shadcn Select binds value.

	// When Year Changes -> Fetch Classrooms, Reset Term & Class
	function onYearChange(id: string) {
		if (id !== selectedYearId) {
			selectedYearId = id;
			selectedTermId = '';
			selectedClassroomId = '';
			fetchClassrooms();
		}
	}

	// When Class/Term Changes -> Filter Courses
	// We can use $effect
	$effect(() => {
		if (canReadCoursePlan && selectedClassroomId && selectedTermId) {
			fetchCourses();
			fetchClassroomActivities();
		} else {
			courses = [];
			classroomActivities = [];
		}
	});

	// Auto-load team instructors when courses list changes — batched to avoid N+1
	let loadedTeamCourseIds = new SvelteSet<string>();

	$effect(() => {
		if (!canReadCoursePlan) return;

		const courseIds = courses.map((c) => c.id).filter((id) => !loadedTeamCourseIds.has(id));
		if (courseIds.length === 0) return;

		batchListCourseInstructors(courseIds)
			.then((res) => {
				const newMap = { ...teamInstructorsMap };
				for (const id of courseIds) {
					newMap[id] = res.data[id] ?? [];
					loadedTeamCourseIds.add(id);
				}
				teamInstructorsMap = newMap;
			})
			.catch(() => {
				/* ignore */
			});
	});

	onMount(initData);
</script>

<svelte:head>
	<title>{data.title} - SchoolOrbit</title>
</svelte:head>

<PageShell
	title="จัดแผนการเรียน (Course Planning)"
	description="กำหนดรายวิชาที่เปิดสอนสำหรับแต่ละห้องเรียนในแต่ละภาคเรียน"
>
	{#snippet actions()}
		<Button
			variant="outline"
			size="sm"
			class="self-start sm:self-auto"
			onclick={openActualExportDialog}
		>
			<FileSpreadsheet class="w-4 h-4 mr-2" />
			ส่งออกใช้จริง
		</Button>
	{/snippet}

	<!-- Filters -->
	{#if !canReadCoursePlan}
		<PageState
			variant="permission"
			title="ไม่มีสิทธิ์ดูแผนการเรียนที่เปิดสอน"
			description="บัญชีนี้เข้า module วางแผนรายวิชาได้ แต่ยังไม่มีสิทธิ์อ่านข้อมูลแผนรายวิชา"
		/>
	{:else}
		<Card.Root>
			<Card.Content class="pt-6">
				<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
					<div class="space-y-2">
						<Label>ปีการศึกษา</Label>
						<Select.Root type="single" value={selectedYearId} onValueChange={onYearChange}>
							<Select.Trigger>
								{structure.years.find((y) => y.id === selectedYearId)?.name || 'เลือกปีการศึกษา'}
							</Select.Trigger>
							<Select.Content>
								{#each structure.years as year (year.id)}
									<Select.Item value={year.id}>{year.name}</Select.Item>
								{/each}
							</Select.Content>
						</Select.Root>
					</div>

					<div class="space-y-2">
						<Label>ภาคเรียน (Semster)</Label>
						<Select.Root type="single" bind:value={selectedTermId}>
							<Select.Trigger disabled={!selectedYearId}>
								{filteredSemesters.find((s) => s.id === selectedTermId)?.term || 'เลือกภาคเรียน'}
							</Select.Trigger>
							<Select.Content>
								{#each filteredSemesters as term (term.id)}
									<Select.Item value={term.id}>เทอม {term.term} ({term.name})</Select.Item>
								{/each}
							</Select.Content>
						</Select.Root>
					</div>

					<div class="space-y-2">
						<Label>ห้องเรียน</Label>
						<Select.Root type="single" bind:value={selectedClassroomId}>
							<Select.Trigger disabled={!selectedYearId}>
								{classrooms.find((c) => c.id === selectedClassroomId)?.name || 'เลือกห้องเรียน'}
							</Select.Trigger>
							<Select.Content class="max-h-[300px]">
								{#each classrooms as room (room.id)}
									<Select.Item value={room.id}>{room.name} ({room.grade_level_name})</Select.Item>
								{/each}
							</Select.Content>
						</Select.Root>
					</div>
				</div>
			</Card.Content>
		</Card.Root>

		<!-- Content -->
		{#if !selectedClassroomId || !selectedTermId}
			<div
				class="h-64 flex flex-col items-center justify-center border rounded-lg bg-muted/10 text-muted-foreground border-dashed"
			>
				<Calendar class="w-12 h-12 mb-4 opacity-20" />
				<p>กรุณาเลือก ปีการศึกษา, ภาคเรียน และ ห้องเรียน เพื่อจัดการข้อมูล</p>
			</div>
		{:else}
			<div class="space-y-4">
				<!-- Summary Statistic Cards -->
				<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
					<Card.Root>
						<Card.Content class="p-3 flex flex-col items-center justify-center text-center">
							<h4 class="text-sm font-medium text-muted-foreground mb-1">วิชาพื้นฐาน</h4>
							<div class="text-xl font-bold">
								{summaryStats.basic.credit.toFixed(1)}
								<span class="text-xs font-normal text-muted-foreground">นก.</span>
							</div>
							<div class="text-xs text-muted-foreground">
								{summaryStats.basic.hours} ชม./เทอม
							</div>
						</Card.Content>
					</Card.Root>
					<Card.Root>
						<Card.Content class="p-3 flex flex-col items-center justify-center text-center">
							<h4 class="text-sm font-medium text-muted-foreground mb-1">วิชาเพิ่มเติม</h4>
							<div class="text-xl font-bold">
								{summaryStats.additional.credit.toFixed(1)}
								<span class="text-xs font-normal text-muted-foreground">นก.</span>
							</div>
							<div class="text-xs text-muted-foreground">
								{summaryStats.additional.hours} ชม./เทอม
							</div>
						</Card.Content>
					</Card.Root>
					<Card.Root>
						<Card.Content class="p-3 flex flex-col items-center justify-center text-center">
							<h4 class="text-sm font-medium text-muted-foreground mb-1">กิจกรรมพัฒนาผู้เรียน</h4>
							<div class="text-xl font-bold">
								{summaryStats.activity.count}
								<span class="text-xs font-normal text-muted-foreground">กิจกรรม</span>
							</div>
							<div class="text-xs text-muted-foreground">
								{summaryStats.activity.periods} คาบ/สัปดาห์
							</div>
						</Card.Content>
					</Card.Root>
					<Card.Root class="bg-primary/5 border-primary/20">
						<Card.Content class="p-3 flex flex-col items-center justify-center text-center">
							<h4 class="text-sm font-medium text-primary mb-1">รวมทั้งสิ้น (วิชา)</h4>
							<div class="text-xl font-bold text-primary">
								{summaryStats.total.credit.toFixed(1)}
								<span class="text-xs font-normal opacity-70">นก.</span>
							</div>
							<div class="text-xs text-muted-foreground">{summaryStats.total.hours} ชม./เทอม</div>
						</Card.Content>
					</Card.Root>
				</div>

				<div class="flex justify-between items-center">
					<h3 class="text-xl font-semibold">
						รายวิชาของห้อง {currentClassroom?.name}
						<Badge variant="outline" class="ml-2"
							>เทอม {filteredSemesters.find((s) => s.id === selectedTermId)?.term}</Badge
						>
					</h3>
					<div class="flex gap-2">
						{#if canManageCoursePlan}
							<Button
								onclick={openAddCourseDialog}
								variant="outline"
								class="flex items-center gap-2"
							>
								<Plus class="w-4 h-4" />
								เพิ่มรายวิชา
							</Button>
						{/if}
						{#if canManageCoursePlan && currentClassroom?.study_plan_version_id}
							<Button
								onclick={() => (showAutoGenerateDialog = true)}
								variant="secondary"
								class="flex items-center gap-2"
							>
								<Wand2 class="w-4 h-4" />
								สร้างรายวิชาอัตโนมัติ
							</Button>
						{/if}
					</div>
				</div>

				<div class="bg-card border rounded-lg overflow-hidden" data-section="courses">
					<Table.Root>
						<Table.Header>
							<Table.Row>
								<Table.Head class="w-[120px]">รหัสวิชา</Table.Head>
								<Table.Head>ชื่อวิชา</Table.Head>
								<Table.Head class="w-[100px]">ประเภท</Table.Head>
								<Table.Head class="text-center w-[100px]">หน่วยกิต</Table.Head>
								<Table.Head>ครูผู้สอน</Table.Head>
								<Table.Head class="text-right w-[80px]"></Table.Head>
							</Table.Row>
						</Table.Header>
						<Table.Body>
							{#if loading}
								<Table.Row>
									<Table.Cell colspan={5} class="p-0">
										<PageSkeleton variant="table" rows={5} columns={5} />
									</Table.Cell>
								</Table.Row>
							{:else if courses.length === 0}
								<Table.Row>
									<Table.Cell colspan={5} class="p-0">
										<PageState title="ยังไม่มีรายวิชา" description="ยังไม่มีรายวิชาในภาคเรียนนี้" />
									</Table.Cell>
								</Table.Row>
							{:else}
								{#each sortedCourses as course (course.id)}
									<Table.Row>
										<Table.Cell class="font-medium">{course.subject_code}</Table.Cell>
										<Table.Cell>
											<div class="font-bold">{course.subject_name_th}</div>
											{#if course.subject_name_en}
												<div class="text-xs text-muted-foreground">{course.subject_name_en}</div>
											{/if}
										</Table.Cell>
										<Table.Cell>
											{#if course.subject_type === 'BASIC'}
												<Badge variant="outline">พื้นฐาน</Badge>
											{:else if course.subject_type === 'ADDITIONAL'}
												<Badge variant="secondary">เพิ่มเติม</Badge>
											{:else if course.subject_type === 'ACTIVITY'}
												<Badge
													variant="secondary"
													class="bg-green-100 text-green-800 hover:bg-green-100 hover:text-green-800 border-green-200"
													>กิจกรรม</Badge
												>
											{:else}
												<span class="text-muted-foreground text-xs">-</span>
											{/if}
										</Table.Cell>
										<Table.Cell class="text-center">
											<div class="text-sm font-medium">
												{course.subject_credit ?? '-'}
												<span class="text-xs font-normal text-muted-foreground">นก.</span>
											</div>
											{#if course.subject_hours !== undefined && course.subject_hours !== null}
												<div class="text-[11px] text-muted-foreground">
													{course.subject_hours} ชม./เทอม
												</div>
											{/if}
										</Table.Cell>
										<Table.Cell>
											<div class="flex items-center gap-2 flex-wrap">
												{#each teamInstructorsMap[course.id] ?? [] as instr (instr.id)}
													<Badge
														variant={instr.role === 'primary' ? 'default' : 'secondary'}
														class="gap-1"
													>
														{instr.role === 'primary' ? 'หลัก' : 'ร่วม'}: {instr.instructor_name ??
															'—'}
														{#if instr.role === 'secondary'}
															<button
																class="ml-1 text-[10px]"
																onclick={() =>
																	handlePromoteToPrimary(course.id, instr.instructor_id)}
																title="เปลี่ยนเป็นครูหลัก"
																disabled={!canManageCoursePlan}
															>
																↑
															</button>
														{/if}
														{#if canManageCoursePlan}
															<button
																class="ml-1 hover:text-destructive"
																onclick={() =>
																	handleRemoveTeamInstructor(course.id, instr.instructor_id)}
															>
																×
															</button>
														{/if}
													</Badge>
												{:else}
													{#if course.instructor_name}
														<span class="text-sm">{course.instructor_name}</span>
													{:else}
														<span class="text-muted-foreground text-sm">- ไม่ระบุ -</span>
													{/if}
												{/each}
												{#if canManageCoursePlan}
													<Button
														variant="outline"
														size="sm"
														class="h-6 text-xs"
														onclick={() => openTeamDialog(course.id)}
													>
														+ เพิ่มครู
													</Button>
												{/if}
											</div>
										</Table.Cell>
										<Table.Cell class="text-right">
											{#if canManageCoursePlan}
												<Button variant="ghost" size="icon" onclick={() => openEditDialog(course)}>
													<Settings class="w-4 h-4" />
												</Button>
												<Button
													variant="ghost"
													size="icon"
													class="text-destructive hover:bg-destructive/10"
													onclick={() => openDeleteDialog(course)}
												>
													<Trash2 class="w-4 h-4" />
												</Button>
											{/if}
										</Table.Cell>
									</Table.Row>
								{/each}
							{/if}
						</Table.Body>
					</Table.Root>
				</div>

				<!-- กิจกรรมพัฒนาผู้เรียน -->
				<div class="space-y-3 pt-4">
					<h3 class="text-xl font-semibold">
						กิจกรรมพัฒนาผู้เรียน
						<Badge variant="outline" class="ml-2">{classroomActivities.length} กิจกรรม</Badge>
					</h3>
					<p class="text-sm text-muted-foreground">
						ช่องกิจกรรมที่ห้องนี้เข้าร่วม — ลบได้จากห้องนี้ (ถ้าเป็นห้องสุดท้าย slot
						จะถูกลบโดยอัตโนมัติพร้อมกิจกรรม/ตารางสอน)
					</p>

					<div class="bg-card border rounded-lg overflow-hidden">
						<Table.Root>
							<Table.Header>
								<Table.Row>
									<Table.Head>ชื่อกิจกรรม</Table.Head>
									<Table.Head class="w-[140px]">ประเภท</Table.Head>
									<Table.Head class="w-[120px]">คาบ/สัปดาห์</Table.Head>
									<Table.Head class="w-[140px]">โหมด</Table.Head>
									<Table.Head class="text-right w-[160px]">การจัดการ</Table.Head>
								</Table.Row>
							</Table.Header>
							<Table.Body>
								{#if loadingActivities}
									<Table.Row>
										<Table.Cell colspan={5} class="h-20 text-center text-muted-foreground">
											<Loader2 class="w-5 h-5 animate-spin mx-auto" />
										</Table.Cell>
									</Table.Row>
								{:else if classroomActivities.length === 0}
									<Table.Row>
										<Table.Cell colspan={5} class="h-20 text-center text-muted-foreground">
											ห้องนี้ยังไม่ได้เข้าร่วมกิจกรรมใดในภาคเรียนนี้
										</Table.Cell>
									</Table.Row>
								{:else}
									{#each classroomActivities as activity (activity.slot_id)}
										<Table.Row>
											<Table.Cell class="font-medium">{activity.name}</Table.Cell>
											<Table.Cell>
												<Badge
													variant="secondary"
													class="bg-green-100 text-green-800 hover:bg-green-100 hover:text-green-800 border-green-200"
												>
													{ACTIVITY_TYPE_LABELS[activity.activity_type] ?? activity.activity_type}
												</Badge>
											</Table.Cell>
											<Table.Cell>
												<span class="font-medium">{activity.periods_per_week}</span>
												<span class="text-xs text-muted-foreground ml-1">คาบ/สัปดาห์</span>
											</Table.Cell>
											<Table.Cell class="text-xs text-muted-foreground">
												{activity.scheduling_mode === 'independent'
													? 'แต่ละห้องจัดเอง'
													: 'จัดพร้อมกันทุกห้อง'}
											</Table.Cell>
											<Table.Cell class="text-right">
												{#if canManageCoursePlan}
													<Button
														variant="outline"
														size="sm"
														class="text-destructive hover:bg-destructive/10"
														onclick={() => handleRemoveClassroomActivity(activity)}
													>
														<Trash2 class="w-3 h-3 mr-1" />
														ลบออกจากห้องนี้
													</Button>
												{/if}
											</Table.Cell>
										</Table.Row>
									{/each}
								{/if}
							</Table.Body>
						</Table.Root>
					</div>
				</div>
			</div>
		{/if}
	{/if}

	<!-- Actual Curriculum Export Dialog -->
	{#if canReadCoursePlan}
		<Dialog.Root bind:open={showActualExportDialog}>
			<Dialog.Content class="sm:max-w-[440px]">
				<Dialog.Header>
					<Dialog.Title>ส่งออกรายวิชาที่ใช้จริง</Dialog.Title>
					<Dialog.Description>
						ดาวน์โหลดรายวิชาและกิจกรรมที่ผูกกับห้องเรียนจริงทุกห้อง ทุกภาคเรียน ในปีการศึกษาที่เลือก
					</Dialog.Description>
				</Dialog.Header>

				<div class="space-y-2 py-2">
					<Label>ปีการศึกษา</Label>
					<Select.Root type="single" bind:value={actualExportYearId}>
						<Select.Trigger class="w-full">
							{structure.years.find((year) => year.id === actualExportYearId)?.name ??
								'เลือกปีการศึกษา'}
						</Select.Trigger>
						<Select.Content>
							{#each structure.years as year (year.id)}
								<Select.Item value={year.id}>{year.name}</Select.Item>
							{/each}
						</Select.Content>
					</Select.Root>
				</div>

				<Dialog.Footer>
					<Button
						variant="outline"
						onclick={() => (showActualExportDialog = false)}
						disabled={exportingActualCurriculum}
					>
						ยกเลิก
					</Button>
					<Button
						onclick={handleExportActualCurriculum}
						disabled={exportingActualCurriculum || !actualExportYearId}
					>
						{#if exportingActualCurriculum}
							<Loader2 class="w-4 h-4 mr-2 animate-spin" />
							กำลังส่งออก...
						{:else}
							<FileSpreadsheet class="w-4 h-4 mr-2" />
							ดาวน์โหลด XLSX
						{/if}
					</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	{/if}

	<!-- Edit Dialog -->
	{#if canManageCoursePlan}
		<Dialog.Root bind:open={showEditDialog}>
			<Dialog.Content class="sm:max-w-[500px]">
				<Dialog.Header>
					<Dialog.Title>แก้ไขรายวิชา</Dialog.Title>
				</Dialog.Header>

				<div class="grid gap-4 py-4">
					<div class="space-y-2">
						<Label>วิชา</Label>
						<div class="font-medium p-2 border rounded bg-muted/20">
							{editingCourse?.subject_code}
							{editingCourse?.subject_name_th}
						</div>
					</div>

					<div class="space-y-2">
						<Label>ครูผู้สอน (Primary Instructor)</Label>
						<Popover.Root bind:open={editTeacherPickerOpen}>
							<Popover.Trigger class="w-full">
								<Button
									variant="outline"
									role="combobox"
									aria-expanded={editTeacherPickerOpen}
									class="w-full justify-between font-normal"
									disabled={submitting}
								>
									<span
										class="truncate {selectedTeacherId === 'unassigned' || !selectedTeacherId
											? 'text-muted-foreground'
											: ''}"
									>
										{#if selectedTeacherId === 'unassigned'}
											- ไม่ระบุ -
										{:else}
											{teacherName(selectedTeacherId) || 'เลือกครู'}
										{/if}
									</span>
									<ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
								</Button>
							</Popover.Trigger>
							<Popover.Content class="w-[--bits-popover-trigger-width] p-0">
								<Command.Root>
									<Command.Input placeholder="ค้นหาครู..." />
									<Command.Empty>ไม่พบครู</Command.Empty>
									<Command.Group class="max-h-[300px] overflow-y-auto">
										<Command.Item
											value="- ไม่ระบุ -"
											onSelect={() => {
												selectedTeacherId = 'unassigned';
												editTeacherPickerOpen = false;
											}}
										>
											<Check
												class="mr-2 h-4 w-4 {selectedTeacherId === 'unassigned'
													? 'opacity-100'
													: 'opacity-0'}"
											/>
											- ไม่ระบุ -
										</Command.Item>
										{#each teachers as teacher (teacher.id)}
											<Command.Item
												value={teacher.name}
												onSelect={() => {
													selectedTeacherId = teacher.id;
													editTeacherPickerOpen = false;
												}}
											>
												<Check
													class="mr-2 h-4 w-4 {selectedTeacherId === teacher.id
														? 'opacity-100'
														: 'opacity-0'}"
												/>
												{teacher.name}
											</Command.Item>
										{/each}
									</Command.Group>
								</Command.Root>
							</Popover.Content>
						</Popover.Root>
					</div>
				</div>

				<Dialog.Footer>
					<Button variant="outline" onclick={() => (showEditDialog = false)}>ยกเลิก</Button>
					<Button onclick={handleUpdateCourse} disabled={submitting}>
						{#if submitting}
							<Loader2 class="w-4 h-4 mr-2 animate-spin" />
						{/if}
						บันทึกการเปลี่ยนแปลง
					</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	{/if}
	<!-- Delete Dialog -->
	{#if canManageCoursePlan}
		<Dialog.Root bind:open={showDeleteDialog}>
			<Dialog.Content class="sm:max-w-[425px]">
				<Dialog.Header>
					<Dialog.Title>ยืนยันการลบวิชา</Dialog.Title>
					<Dialog.Description>
						คุณต้องการลบวิชา <strong
							>{deletingCourse?.subject_code} {deletingCourse?.subject_name_th}</strong
						> ออกจากห้องเรียนนี้ใช่หรือไม่?
					</Dialog.Description>
				</Dialog.Header>
				<Dialog.Footer>
					<Button variant="outline" onclick={() => (showDeleteDialog = false)}>ยกเลิก</Button>
					<Button variant="destructive" onclick={handleRemove} disabled={submitting}>
						{#if submitting}
							<Loader2 class="w-4 h-4 mr-2 animate-spin" />
						{/if}
						ยืนยันลบ
					</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	{/if}
	<!-- Auto-Generate Dialog -->
	{#if canManageCoursePlan}
		<Dialog.Root bind:open={showAutoGenerateDialog}>
			<Dialog.Content class="sm:max-w-[500px]">
				<Dialog.Header>
					<Dialog.Title class="flex items-center gap-2">
						<Wand2 class="w-5 h-5" />
						สร้างวิชา + กิจกรรมอัตโนมัติจากแผนการเรียน
					</Dialog.Title>
					<Dialog.Description>
						ระบบจะดึงทั้ง <b>รายวิชา</b> และ <b>กิจกรรมพัฒนาผู้เรียน</b> จากหลักสูตรที่ห้องนี้ใช้ แล้วสร้างให้อัตโนมัติตามระดับชั้น
						+ ภาคเรียนที่เลือก (ครูทีมจะถูก copy จากคลังรายวิชาให้ด้วย)
					</Dialog.Description>
				</Dialog.Header>

				<div class="space-y-4 py-4">
					<div class="p-4 bg-muted/50 rounded-lg space-y-2">
						<div class="flex items-center justify-between">
							<span class="text-sm font-medium">ห้องเรียน:</span>
							<Badge variant="secondary">{currentClassroom?.name}</Badge>
						</div>
						<div class="flex items-center justify-between">
							<span class="text-sm font-medium">ภาคเรียน:</span>
							<Badge variant="secondary">
								เทอม {filteredSemesters.find((s) => s.id === selectedTermId)?.term}
							</Badge>
						</div>
					</div>

					<div
						class="p-4 bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-900 rounded-lg"
					>
						<div class="flex gap-2">
							<div class="text-blue-600 dark:text-blue-400 mt-0.5">ℹ️</div>
							<div class="text-sm text-blue-900 dark:text-blue-100 space-y-1">
								<p class="font-medium">หมายเหตุ:</p>
								<ul class="list-disc list-inside space-y-1 text-xs">
									<li>รายวิชา/กิจกรรมที่มีอยู่แล้วจะไม่ถูกสร้างซ้ำ</li>
									<li>ต้องการเพิ่ม/เอาวิชาออก → แก้ที่หลักสูตรแล้วกดซ้ำได้</li>
									<li>สามารถลบหรือแก้ไขรายวิชาที่สร้างแล้วในห้องนี้ได้</li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				<Dialog.Footer>
					<Button
						variant="outline"
						onclick={() => (showAutoGenerateDialog = false)}
						disabled={autoGenerating}
					>
						ยกเลิก
					</Button>
					<Button onclick={handleAutoGenerate} disabled={autoGenerating}>
						{#if autoGenerating}
							<Loader2 class="w-4 h-4 mr-2 animate-spin" />
							กำลังสร้าง...
						{:else}
							<Wand2 class="w-4 h-4 mr-2" />
							สร้างวิชา + กิจกรรม
						{/if}
					</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	{/if}

	<!-- Add Course Dialog -->
	{#if canManageCoursePlan}
		<Dialog.Root bind:open={showAddCourseDialog}>
			<Dialog.Content class="max-w-2xl">
				<Dialog.Header>
					<Dialog.Title>เพิ่มรายวิชา</Dialog.Title>
					<Dialog.Description>
						เพิ่มวิชาเข้าห้อง {currentClassroom?.name} — ครูประจำวิชา (default) จะถูกใส่ให้อัตโนมัติ
					</Dialog.Description>
				</Dialog.Header>

				<Tabs.Root bind:value={addCourseTab} class="w-full">
					<Tabs.List class="grid w-full grid-cols-2">
						<Tabs.Trigger value="plan" disabled={!currentClassroom?.study_plan_version_id}>
							จากหลักสูตร ({planSubjectsForAdd.filter(
								(sps) => !courses.some((c) => c.subject_id === sps.subject_id)
							).length})
						</Tabs.Trigger>
						<Tabs.Trigger value="catalog">
							จากคลังวิชาทั้งหมด ({catalogSubjectsForAdd.filter(
								(s) => !courses.some((c) => c.subject_id === s.id)
							).length})
						</Tabs.Trigger>
					</Tabs.List>

					<Tabs.Content value="plan" class="mt-3">
						<p class="text-xs text-muted-foreground mb-2">
							วิชาที่หลักสูตรกำหนดแต่ยังไม่อยู่ในห้องนี้ (แนะนำใช้ path นี้เพื่อ sync กับหลักสูตร)
						</p>
						<div class="max-h-[400px] overflow-y-auto divide-y rounded border">
							{#if addCourseLoading}
								<div class="py-4 text-center text-muted-foreground text-sm">
									<Loader2 class="w-4 h-4 animate-spin inline mr-1" /> กำลังโหลด...
								</div>
							{:else}
								{@const availablePlan = planSubjectsForAdd.filter(
									(sps) => !courses.some((c) => c.subject_id === sps.subject_id)
								)}
								{#each availablePlan as sps (sps.id)}
									<div class="flex items-center gap-2 px-3 py-2 text-sm">
										<span class="flex-1 truncate">
											<span class="font-medium">{sps.subject_code}</span>
											<span class="text-muted-foreground ml-2">{sps.subject_name_th}</span>
											{#if sps.subject_type === 'BASIC'}
												<Badge variant="outline" class="ml-2 text-[10px]">พื้นฐาน</Badge>
											{:else if sps.subject_type === 'ADDITIONAL'}
												<Badge variant="secondary" class="ml-2 text-[10px]">เพิ่มเติม</Badge>
											{/if}
										</span>
										<Button
											variant="outline"
											size="sm"
											class="h-7"
											onclick={() => handleAddCourse(sps.subject_id)}
											disabled={addCourseSaving === sps.subject_id}
										>
											{#if addCourseSaving === sps.subject_id}
												<Loader2 class="w-3 h-3 animate-spin" />
											{:else}
												เพิ่ม
											{/if}
										</Button>
									</div>
								{:else}
									<p class="text-xs text-muted-foreground italic text-center py-3">
										วิชาในหลักสูตรถูกเพิ่มครบแล้ว
									</p>
								{/each}
							{/if}
						</div>
					</Tabs.Content>

					<Tabs.Content value="catalog" class="mt-3">
						<p class="text-xs text-muted-foreground mb-2">
							คลังวิชาทั้งหมด — ใช้เมื่อห้องนี้ต้องการวิชา**นอกหลักสูตร** (เช่น ห้องพิเศษ/ตกซ้ำชั้น)
						</p>
						<div class="max-h-[400px] overflow-y-auto divide-y rounded border">
							{#if addCourseLoading}
								<div class="py-4 text-center text-muted-foreground text-sm">
									<Loader2 class="w-4 h-4 animate-spin inline mr-1" /> กำลังโหลด...
								</div>
							{:else}
								{@const availableCatalog = catalogSubjectsForAdd.filter(
									(s) => !courses.some((c) => c.subject_id === s.id)
								)}
								{#each availableCatalog as s (s.id)}
									<div class="flex items-center gap-2 px-3 py-2 text-sm">
										<span class="flex-1 truncate">
											<span class="font-medium">{s.code}</span>
											<span class="text-muted-foreground ml-2">{s.name_th}</span>
											{#if s.type === 'BASIC'}
												<Badge variant="outline" class="ml-2 text-[10px]">พื้นฐาน</Badge>
											{:else if s.type === 'ADDITIONAL'}
												<Badge variant="secondary" class="ml-2 text-[10px]">เพิ่มเติม</Badge>
											{/if}
										</span>
										<Button
											variant="outline"
											size="sm"
											class="h-7"
											onclick={() => handleAddCourse(s.id)}
											disabled={addCourseSaving === s.id}
										>
											{#if addCourseSaving === s.id}
												<Loader2 class="w-3 h-3 animate-spin" />
											{:else}
												เพิ่ม
											{/if}
										</Button>
									</div>
								{:else}
									<p class="text-xs text-muted-foreground italic text-center py-3">
										ไม่มีวิชาในคลังที่ยังไม่ได้เพิ่ม
									</p>
								{/each}
							{/if}
						</div>
					</Tabs.Content>
				</Tabs.Root>

				<Dialog.Footer>
					<Button variant="outline" onclick={() => (showAddCourseDialog = false)}>ปิด</Button>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	{/if}

	<!-- Team Teaching Dialog -->
	{#if canManageCoursePlan}
		<Dialog.Root bind:open={showTeamDialog}>
			<Dialog.Content class="max-w-sm">
				<Dialog.Header>
					<Dialog.Title>เพิ่มครูผู้สอน</Dialog.Title>
				</Dialog.Header>
				<div class="space-y-2 py-2">
					<Label>ครู</Label>
					<Popover.Root bind:open={teamTeacherPickerOpen}>
						<Popover.Trigger class="w-full">
							<Button
								variant="outline"
								role="combobox"
								aria-expanded={teamTeacherPickerOpen}
								class="w-full justify-between font-normal"
								disabled={teamInstructorAdding}
							>
								<span class="truncate">
									{teacherName(teamDialogSelectedInstructor) || 'เลือกครู'}
								</span>
								<ChevronsUpDown class="ml-2 h-4 w-4 shrink-0 opacity-50" />
							</Button>
						</Popover.Trigger>
						<Popover.Content class="w-[--bits-popover-trigger-width] p-0">
							<Command.Root>
								<Command.Input placeholder="ค้นหาครู..." />
								<Command.Empty>ไม่พบครู</Command.Empty>
								<Command.Group class="max-h-[280px] overflow-y-auto">
									{#each teachers as teacher (teacher.id)}
										<Command.Item
											value={teacher.name}
											onSelect={() => {
												teamDialogSelectedInstructor = teacher.id;
												teamTeacherPickerOpen = false;
											}}
										>
											<Check
												class="mr-2 h-4 w-4 {teamDialogSelectedInstructor === teacher.id
													? 'opacity-100'
													: 'opacity-0'}"
											/>
											{teacher.name}
										</Command.Item>
									{/each}
								</Command.Group>
							</Command.Root>
						</Popover.Content>
					</Popover.Root>

					<Label>บทบาท</Label>
					<Select.Root type="single" bind:value={teamDialogRole}>
						<Select.Trigger class="w-full" disabled={teamInstructorAdding}
							>{teamDialogRole === 'primary' ? 'ครูหลัก' : 'ครูร่วม'}</Select.Trigger
						>
						<Select.Content>
							<Select.Item value="primary">ครูหลัก</Select.Item>
							<Select.Item value="secondary">ครูร่วม</Select.Item>
						</Select.Content>
					</Select.Root>
				</div>
				<Dialog.Footer>
					<Button
						variant="outline"
						onclick={() => {
							showTeamDialog = false;
						}}
						disabled={teamInstructorAdding}>ปิด</Button
					>
					<LoadingButton
						onclick={handleAddTeamInstructor}
						loading={teamInstructorAdding}
						disabled={!teamDialogSelectedInstructor || teamInstructorAdding}
						loadingLabel="กำลังเพิ่ม..."
					>
						เพิ่ม
					</LoadingButton>
				</Dialog.Footer>
			</Dialog.Content>
		</Dialog.Root>
	{/if}
</PageShell>
